alphagov/govuk_elements

views/index.html

Where a hackpad exists for a topic, link to this - rather than to the
elements feedback page.
- Add new link to Progressive disclosure hackpad
- Link icons and images to Iconography hackpad
- Link data feedback to Tables hackpad
- Link buttons to Navigation buttons hackpad
- Link errors and validation to Error messaging hackpad

Improve discusssion links to hackpads

---

views/index.html

The best way to explain why we’d like people not to use native select
tags is to get them to watch this talk.
Also mention the HTML select element (next to drop-down lists), so it’s clear we’re talking
about the same thing.

Add link to burn your select tags

---

views/snippets/form_checkboxes.html
views/snippets/form_focus.html
views/snippets/form_inset_checkboxes.html
views/snippets/form_inset_radios.html
views/snippets/form_radio_buttons.html
views/snippets/form_radio_buttons_inline.html

[selection-buttons.js](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/selection-buttons.js) requires a parent `<form>` wrapper, add this
to any examples which demonstrate chunky radio buttons.
Also remove the `.form` class, and any form attributes for form
examples.
[This fixes issue 155](https://github.com/alphagov/govuk_frontend_toolkit/issues/155), and [issue 54] (https://github.com/alphagov/govuk_elements/issues/54). 
The `<form>` element wasn't previously added to the elements code snippets to keep them short.

Add a form wrapper to radio examples

---

public/sass/elements/forms/_form-block-labels.scss

This should be 10px, the same as the space between block labels.

Reduce spacing to the right of block labels

---

public/javascripts/vendor/details.polyfill.js
views/patterns/details_summary.html

The current polyfill wasn't correctly detecting the "open" attribute and was firing twice in Chrome, 
when the summary was clicked.
For now, it has two checks - first for native support, which uses the boolean "open" attribute.  Then for non-native support, which checks for an "open" attribute with an empty value, otherwise "open" is
undefined (not present) and the details content should be closed.
For non-native support, an open or closed arrow (pointing right or down) is added, and styled to look like the native arrow in Chrome - depending on the initial "open" state. This arrow is hidden from assistive technology using `role="presentation"`. [Read the W3C Recommendation here](http://www.w3.org/TR/wai-aria/roles#presentation).
`<details role="group">`
The implicit role for `<details>` …

Improve details summary polyfill

---

public/javascripts/application.js

Rails creates form elements with square brackets, for example customer[name].  These need to be escaped in application.js showHideToggledContent()

escape square brackets in element name

---

public/javascripts/application.js

There was a bug in the escape element names PR I submitted last week; it was manifested by a div being un-hidden on clicking a radio button wasn't re-hidden when clicking another radio button.  This is the fix.

bug fix escaping element names

---

public/sass/elements-page.scss
views/index.html
views/snippets.html
views/snippets/phase_banner_alpha.html
views/snippets/phase_banner_beta.html

Move content from the [Service Design Manual - Patterns page](https://www.gov.uk/service-manual/user-centred-design/resources/patterns/alpha-beta).
GOV.UK elements explains how to make use of the Sass mixins provided by the [GOV.UK frontend toolkit](https://github.com/alphagov/govuk_frontend_toolkit) - this content should sit here.

Add guidance on phase banners

---

.scss-lint.yml
Gruntfile.js
package.json
public/sass/elements/_details.scss
public/sass/elements/_elements-typography.scss
public/sass/elements/_forms.scss
public/sass/elements/_helpers.scss
public/sass/elements/_icons.scss
public/sass/elements/_layout.scss
public/sass/elements/_lists.scss
public/sass/elements/_panels.scss
public/sass/elements/_tables.scss
public/sass/elements/forms/_form-date.scss
public/sass/elements/forms/_form-validation.scss

Use grunt-scss lint to pick up any inconsistencies between the GOV.UK elements scss files.
The .scss-lint.yml file defines the rules we are ignoring for now, these are:
- allow double string quotes
- allow more verbose shorthand 
- allow ID selectors (there is only one ID used - for #content)
- allow qualifying elements (this is used for th.numeric and specific table styles)
- single line per selector (the reset.scss file hasn't been split onto multiple lines)
These changes include:
- adding an empty line between blocks
- removing spaces between params
- merging rules where possible
- replacing hex values with their corresponding colour variables

Add grunt scss lint

---

govuk/public/javascripts/govuk/analytics/google-analytics-classic-tracker.js
govuk/public/javascripts/govuk/analytics/tracker.js
govuk/public/javascripts/govuk/multivariate-test.js
govuk/public/sass/_colours.scss
package.json

- Fix: Make the error colour a darker red for greater contrast and to
meet WCAG 2.0 AAAA
(this was meant to go into 3.3.1 but was lost from history)
- Add `$focus-colour` variable (#180)
- multivariate-test.js: add support for using Google Content
Experiments as the reporting
backend for multivariate tests
- Fix: Make the error colour a darker red for greater contrast and to
meet WCAG 2.0 AAAA

Bump govuk frontend toolkit to 3.4.1

---

views/index.html
views/snippets/form_focus.html

There is now a `$focus-colour` variable, use this rather than `$yellow`.
Update the hex value for `$error-colour` to match the govuk front end
toolkit.
These changes show those in version 3.4.1 of the govuk frontend toolkit.
PR for reference: https://github.com/alphagov/govuk_frontend_toolkit/pull/181

Use new colour variable names and hex values

---

public/javascripts/vendor/details.polyfill.js
views/patterns/details_summary.html

The details polyfill was preventing the space key from being entered, for the
entire document. It now only prevents the space key for summary
elements, where it prevents the page from scrolling as the widget is
opened.

Fix spaces within form fields

---

public/sass/elements-page.scss
views/index.html

- Add .swatch-colourname classes for discovery and live
- Add discovery and live colour swatches to index page
Check against govuk front end toolkit:
$discovery-colour: $fuschia: #912b88;
$live-colour : $grass-green: #85994b;
This reflects the changes made by @edwardhorsford in the [govuk front end toolkit 3.5.1](https://github.com/alphagov/govuk_frontend_toolkit_npm/commit/0d86d11004afad88a612d2a63f329a53cd46278c).
Screenshot below.

Add swatches for discovery and live colours

---

public/sass/elements/_helpers.scss

Some users of the GOV UK Elements sass have their own existing file structure for image assets. When the $path was added it created urls starting with /public/images but it would be more flexible to allow other users to set their own value. By making the assignment optional, if a developer has defined $path in their top level file it will use that instead. Alternatively move the $path assignment out of the helper and up to the main.scss file

Only set $path if not already set

---

app.js
public/javascripts/application.js
public/sass/elements-page.scss
public/sass/elements/_forms.scss
public/sass/elements/forms/_form-block-labels.scss
public/sass/elements/forms/_form-validation.scss
routes.js
views/examples/form-validation-multiple-questions.html
views/examples/form-validation-single-question-radio.html
views/index.html
views/snippets.html
views/snippets/form_date.html
views/snippets/form_error_multiple.html
views/snippets/form_error_multiple_show_errors.html
views/snippets/form_error_radio.html
views/snippets/form_error_radio_show_errors.html
views/snippets/form_inset_checkboxes.html
views/snippets/form_inset_radios.html

There has been rather a lot of back-and-forth in the previous PR while this was tested further.
This is a new clean branch with the proposed changes to the errors and validation section.
It can be previewed here: https://govuk-elements-test.herokuapp.com/
Our current thinking about validation messages is:
- encourage the use of error summary boxes, as close to the top of the main content as possible
- provide a link to correct each error within the summary box
- error text must sit within either the label or legend for the question it relates to, to ensure it is read out by Assistive Technology
There are two example pages, one which shows how to display errors for a single question - a group of radio buttons and another which shows how to display errors for multiple questions. They have …

New errors and validation guidance for review

---

public/sass/elements/_buttons.scss
public/sass/elements/_forms.scss

These changes match those [already made to the GOV.UK prototype kit]( https://github.com/alphagov/govuk_prototype_kit/commit/da465756c1ed08e2c25735924ee2317abc508b0a).

Make buttons full width for smaller screens

---

public/sass/elements/_buttons.scss

The current class name is `button-get-started` which can be confusing and hard to remember if you don't have that text on the button.
The example says 'Start now' - I propose just having `button-start` so it's agnostic to what text is on the button.
Continue to support `button-get-started` as an alias for now, so it doesn't break people's code

Change to 'button-start' class name

---

public/sass/elements/_forms.scss
routes.js
views/test/form_elements.html

This PR creates a new test page for form elements and shows the difference when `-webkit-appearance: none` is removed from `.form-control`. 
Screenshots:
Before:
After:

Form control test page

---

public/javascripts/vendor/details.polyfill.js
views/patterns/details_summary.html

This includes the fixes made by @gavboulton in #95 and also removes the `open` attribute for non-native details when the widget is closed and sets it when the widget is re-opened.
It also adds two more details elements to the test page, with both `<details open>` and `<details open="open">` to ensure the polyfill is setting and removing the open attribute as the widget is opened and closed.
http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-details-element
http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#boolean-attribute
cc @tombye.

Fixes for the details summary polyfill

---

public/sass/elements/forms/_form-block-labels.scss

The new size matches the size of the custom radio buttons used on Verify (29×29).
IE8 doesn’t resize radios or checkboxes, so there’s an override to pull it up to a reasonable place. IE9 doesn’t position properly on resize but we probably want to check the numbers as not many people still use Vista and IE10 and 11 are available on Windows 7.
What does everyone think? Worth pulling in? Too many browser discrepancies?
Screenshots of the below in various browsers:
*Chrome (Android)*
*Chrome (OS X)*
*Chrome (Windows 10)*
*Firefox (OS X)*
*Firefox (Windows 10)*
*Safari (OS X)*
*Safari (iOS)*
*IE8 (Windows 7)*
*IE9 (Windows 7)*
*IE11 (Windows 10)*
*Edge (Windows 10)*
*IE (Windows Mobile)*

Update block label inputs to be bigger

---

views/snippets/buttons_button.html
views/snippets/buttons_button_disabled.html
views/snippets/form_checkbox_native.html
views/snippets/form_checkboxes.html
views/snippets/form_date.html
views/snippets/form_inset_checkboxes.html
views/snippets/form_inset_radios.html
views/snippets/form_spacing.html

In order for the inputs to function in code, they must have the `name` attribute. I've added this so that people copying the snippets don't have to add any extra code.
For inputs in a series (checkboxes) I've used the `variable[]` naming convention from PHP, but I don't know if that works in Node/Express.

Add attributes to snippets

---

views/examples/example_details_summary.html

- Add an intro paragraph describing the purpose of the page
- Link to a support table from Can I Use? to show browser support
- Link to the polyfill used by GOV.UK elements on Github
- Describe the ARIA attributes set by the polyfill
- Add subheadings to separate each example
Here's a screenshot showing the changes:

Add an introduction to the details summary page

---

views/examples/example_forms.html

I think we should remove these from the example, as we're pretty much decided that the 'Back' link goes at the top of the page. And 'Skip' links aren't very commonly used.

Remove links from below the submit button

---

views/guide_layout.html

Recommend using a grid split in a 2/3, 1/3 page layout 
- to prevent overly long lines of text.
This applies to all content, not just body text. 
Add this guidance to the layout section.
cc. @edwardhorsford, @timpaul.

Update guidance on page width and line length

---

public/sass/elements/_details.scss
public/sass/elements/_panels.scss
views/snippets/form_inset_checkboxes.html
views/snippets/form_inset_radios.html
views/snippets/typography_inset_text.html

**Increase the border width for indented 'info' panels**
These are used to highlight supporting information on GOV.UK and have a 10px left hand border.
The current style for indented panels of text:
Proposed change to match GOV.UK:
**Fix the spacing of toggled content within forms** 
Before:
After:
Also, increase the width of the indented panel for toggled content in forms to 5px. All units used elsewhere are multiples of 5px.

Fix panel spacing

---

public/sass/elements/_components.scss
public/sass/main.scss
views/guide_colour.html

These box styles use a .govuk-prefix, in the same way as govuk
components. 
These styles will be moved either into the govuk-component
library, or to the front-end toolkit, but for now can sit here - to
identify common patterns between govuk pages (e.g. bank holidays) and
service pages - here the example is the transaction end page.
Screenshot below:

Add govuk prefixed styles for box highlight

---

public/sass/elements/_forms.scss

Increase this to 2px and change the colour from a light grey
($border-colour) to a darker grey ($grey-1).
The current border style:
With a darker colour and thicker border:

Increase the width of the border and make the border color darker for form controls

---

public/sass/elements-page.scss
public/sass/elements/_lists.scss
views/examples/example_form_validation_multiple_questions.html
views/examples/example_form_validation_single_question_radio.html
views/examples/example_typography.html
views/guide_colour.html
views/guide_data.html
views/guide_errors.html
views/guide_form_elements.html
views/guide_icons_images.html
views/guide_layout.html
views/guide_typography.html
views/snippets/typography_lists.html

Don't apply list styles to unordered and ordered list elements
There will be cases where the styles set for ul and ol have to be
overridden. 
Instead, use a class of .list to apply these styles.

Add list class for lists

---

public/sass/elements/_buttons.scss
public/sass/elements/_details.scss
public/sass/elements/_elements-typography.scss
public/sass/elements/_forms.scss
public/sass/elements/_helpers.scss
public/sass/elements/_icons.scss
public/sass/elements/_layout.scss
public/sass/elements/_panels.scss
public/sass/elements/_tables.scss
public/sass/elements/forms/_form-block-labels.scss
public/sass/main.scss

The aim of this PR is to put all the Sass import statements in once place, with the Sass variables and mixins from the govuk front end toolkit first.
It also moves any Sass imports within partials to the top level - so the main.scss file shows all files imported - this removes the imports from the bottom of forms, for block labels, date of birth and validation.

Move govuk frontend toolkit dependencies

---

CONTRIBUTING.md
README.md

- Add details about the Sass dependency on the GOV.UK front end toolkit
- Show how the Sass files within /public/sass/elements are imported
- Explain which files are used only to style the page furniture
- Add an example for running Wraith
- Request that issues are raised with this repository
cc. @fofr, @robinwhittleton.

Update the README

---

public/sass/elements-page.scss
public/sass/elements/_buttons.scss

Spacing for form elements is made consistent using the .form-group
clearing wrapper, remove the top and right margins, currently added to all buttons.
Also remove overrides for spacing underneath buttons within example boxes.
cc. @tyom, @robinwhittleton.

Remove button margins

---

public/sass/elements-page.scss
views/guide_colour.html

The Sass variable $govuk-blue exists in the frontend toolkit, for
#005ea5.
Add this swatch to the colour palette.

Add a colour swatch for $govuk-blue

---

public/sass/elements/_elements-typography.scss

This was an attempt to smooth the edges of the left pointing triangle
in Firefox, as they appeared jagged.
Unfortunately, this caused the following Sass compilation error in the Rails govuk prototype template: 
Base-level rules cannot contain the
parent-selector-referencing character '&'.
Since this “fix” is no longer required, removing these rules fixes this.
Screenshots of Firefox and Safari, to compare:

Remove Firefox "fix" for arrow edges

---

public/sass/elements/_layout.scss

I regularly type `.column-two-thirds`, then `.column-one-third`, then realise this classname is incorrect.
GOV.UK elements currently follows the usage examples from the govuk front end toolkit to name these grid columns. https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_grid_layout.scss#L71
This PR adds an extra class, to follow the naming convention you would expect for a 1/3 width column, given the naming convention for the 2/3 width column.

Add .column-one-third class to layout

---

lib/template-config.js
views/includes/cookie_message.html
views/layout.html
views/layout_example.html

- Use the [same cookie message as govuk_template](https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb#L73)
- Move the default message to `lib/config.js`, this matches the [govuk_prototype_kit](https://github.com/alphagov/govuk_prototype_kit/pull/92)
- Remove cookie message include as this is no longer required
Screenshot below:

Update cookie message to match govuk template default

---

public/sass/elements/_layout.scss
public/sass/elements/_lists.scss
public/sass/elements/_panels.scss
views/examples/example_details_summary.html
views/examples/example_form_validation_multiple_questions.html
views/examples/example_form_validation_single_question_radio.html
views/examples/example_grid_layout.html
views/examples/example_radios_checkboxes.html
views/examples/example_typography.html
views/guide_buttons.html
views/guide_colour.html
views/guide_data.html
views/guide_errors.html
views/guide_form_elements.html
views/guide_icons_images.html
views/guide_layout.html
views/guide_typography.html
views/index.html
views/layout_example.html
views/snippets/form_inset_checkboxes.html
views/snippets/form_inset_radios.html
views/snippets/layout_grid_halves.html
views/snippets/layout_grid_quarters.html
views/snippets/layout_grid_thirds.html
views/snippets/layout_grid_thirds_one_third_two_thirds.html
views/snippets/layout_grid_thirds_two_thirds_one_third.html
views/snippets/layout_spacing.html
views/snippets/typography_inset_text.html
views/snippets/typography_lists.html
views/snippets/typography_progressive_disclosure.html

Use a common base class and modifier class pattern for lists, panels, icons (the changes to icons have already been made in #129).
Also use a common naming convention for grid columns, add `.column-one-third` and `.column-one-half`, update the examples to show use of these new classnames (while .column-third and .column-half remain, this isn't a breaking change - but aims to make our classnames for layout easier to guess).
cc. @robinwhittleton.

Use a common naming convention

---

public/sass/elements/_elements-typography.scss
public/sass/elements/_icons.scss
views/guide_icons_images.html
views/guide_typography.html
views/snippets/typography_legal_text.html

Add guidance and example of warning text, using the exclamation icon.

Add legal text example

---

public/sass/elements/_icons.scss
routes.js
views/examples/example_icons.html
views/guide_icons_images.html

- Create an example page and link to it from the Icons and images section.
- Create a mixin to generate the rules for each icon, to avoid repetition. 
The mixin requires the icon name, width and height and optional subfolder - for the step icons.
(The subfolder option can be removed once the step icons are rebuilt using only CSS)
- Use a base class and modifier class for each icon
Here is a screenshot of the Icons example page:
cc. @fofr, @robinwhittleton.

Show icons in the govuk frontend toolkit

---

public/sass/elements-page.scss
views/guide_colour.html

Thanks to @edwardhorsford for spotting this one.
Before:
After:

Fix: Hex value for error colour, displayed above $error-colour variable

---

public/sass/elements/_elements-typography.scss

This now uses the strong element.
Before:
After:

Fix: Update the selector used by the notice styles

---

public/sass/elements/_panels.scss

Fix: set only a left border for panels

---

public/sass/elements-page.scss
views/examples/example_icons.html
views/guide_icons_images.html

Add missing `.list` class to lists.
`list-style-type: none`, should probably be a default, so the `.list` class isn't needed to apply this.
This relates to #134, these HTML element styles should be set in `_base.scss`.
I'll raise an issue.

Fix missing list classes

---

views/examples/example_typography.html
views/snippets/typography_lists.html

They don’t have bullets, or numbers and use the default .list spacing.

Lists of links don't require a modifier class

---

package.json

- Find and auto-start JavaScript modules from markup:
`data-module="module-name"`(PR #227)
- Add helpers partial for functions
- Add px to em function and documentation

Bump govuk frontend toolkit to 4.5.0

---

.travis.yml

This PR modifies the existing deployment task to also add deployment to production. 
The master branch is deployed to a test Heroku app govuk-elements-test.herokuapp.com.
The most recent tagged build is deployed to production govuk-elements.herokuapp.com.
Deploying to Heroku is currently a manual process, this helps to ensure GOV.UK elements is kept up-to-date.

Split deploy for staging and production

---

.travis.yml
package.json

Reference the locally-installed version of Grunt for the 'test' task to check that the app runs.
This updates the govuk elements Travis file to match the [govuk prototype kit](https://github.com/alphagov/govuk_prototype_kit/pull/112).

Use locally installed grunt

---

public/sass/elements/_lists.scss

These styles will be updated to match the govuk related content
component, remove the .list-links classname. [This has already been
removed from the lists snippet](https://github.com/alphagov/govuk_elements/commit/f3907a5038a845847b6f08a451e26e1cca33bc42) and was left here by mistake.

Remove this style for the spacing under related links

---

.npmignore
.travis.yml
README.md
package.json

One solution, to resolve #155 - would be to create a govuk_elements_sass_npm repo [as already exists for the govuk frontend toolkit](https://github.com/alphagov/govuk_frontend_toolkit_npm), with only the Sass files whitelisted, as below.
Here, updating `package.json` would make it possible to request only the Sass files, without the rest of the govuk elements application.
These changes make the files available within `public/sass`, excluding those in `.npmignore`.

Update package json to publish govuk-elements-sass

---

.travis.yml

When validated using the Travis command line tool, the following errors
occur:
Warnings for .travis.yml:
[x] value for deploy section is empty, dropping
[x] in deploy section: missing key provider
Removing the matrix field fixes this.

Remove matrix, this is causing deploy to fail

---

views/snippets/form_error_multiple.html
views/snippets/form_error_multiple_show_errors.html
views/snippets/form_error_radio.html
views/snippets/form_error_radio_show_errors.html

We avoid using `(s)` in content on GOV.UK - the preference is to use the plural form where it's ambiguous.
I know these are just examples, but would be good to match content style.

Make error messages plural rather than using (s)

---

routes.js

Change the section to `icons-images`, so the middle breadcrumb links back to the “Icons and images” section.

Fix the breadcrumbs for Icons and images

---

.npmignore
package.json

The current [govuk-elements-sass module](https://registry.npmjs.org/govuk-elements-sass) contains all files in `/public/sass/`, including those which are set to be ignored by the `.npmignore` file.
Rather than list files to be ignored within `/public/sass/` by setting `files` in package.json, list all files in the repository to be ignored in the `.npmignore` file and remove `files` from package.json.
Related: https://github.com/npm/npm/issues/7030
Testing this using npm pack works as expected.

Fix package json as npmignore isnt working

---

package.json
views/guide_colour.html

The latest version updates the _colours.scss partial, so
$link-hover-colour is now $light-blue.
Update the HEX value in the GOV.UK elements colour swatch for
$link-hover-colour to reflect this.
This is the corresponding PR for elements, @robinwhittleton.

Bump the govuk frontend toolkit to 4.6.1

---

package.json

When `govuk-elements-sass` is installed, a warning is shown for the engine -
setting this to be greater than or equal to 4.0.0 fixes this.
@edwardhorsford, let me know if this fixes #165.

Fix warning for npm engine

---

views/snippets/form_date.html

This should be `2016`, and fixes #174.
cc. @robinwhittleton, @joelanman, @henryhadlow.

Update max for date pattern to include this year

---

views/examples/example_date.html
views/examples/example_details_summary.html
views/examples/example_form_elements.html
views/examples/example_form_validation_multiple_questions.html
views/examples/example_form_validation_single_question_radio.html
views/examples/example_grid_layout.html
views/examples/example_typography.html

All main content should sit in a 2/3 column grid.
Add `.grid-row` and `.column-two-thirds` divs where they are missing.
This is most noticeable on the Errors and validation pages - the error message summary box should also be constrained by a wrapper which is 2/3 of the page width.
Screenshot before:
Screenshots after:

Add missing 2/3 width grid wrappers to example pages

---

views/includes/breadcrumb.html

This was copied from the [govuk-breadcrumb component](https://github.com/alphagov/static/pull/737), which has since removed `role=“breadcrumbs”`.
cc. @robinwhittleton, @fofr.

Remove invalid ARIA role

---

public/sass/elements/_tables.scss

All body copy should be the same, at 19px, this includes tabular data.
GOV.UK has tables set at 16px, these are to stand out from large areas
of body copy at 19px.
Add a .table-font-xsmall class, to recreate these smaller table styles.
After:
16px
19px

Use 19px as the default font size for tabular data

---

package.json

- Add CSS hook (`.js-hidden`) for hiding content when JS is enabled.
Some apps have an equivalent hook, which can be removed once upgraded
to this version

Bump govuk template to 0.17.0

---

views/snippets/form_date.html

This will cause screen readers to announce the hint (after they
announce the legend and/or form label for the field).
cc. @aduggin.

Use aria-describedby to associate the hint with the form fields

---

package.json

- Add websafe organisation colours
- Split colours into two files with backwards-compatible colours.scss
replacement
- Add GOV.UK lint to lint scss files (PR #260)
- Remove reference to old colour palette (PR #256)
- Fix link to GOV.UK elements - tabular data
- Update DEFRA brand colour to new green (PR #249)
- Pass cohort name to analytics when using multivariate test (PR #251)
- Add 'mailto' tracking to GOV.UK Analytics (PR #244)

Update the govuk_frontend_toolkit to 4.9.0

---

README.md

Remove the code block showing the list of partials imported by GOV.UK elements as this makes the
rest of the README harder to scan.
This fixes #192.

Make the README easier to read

---

public/sass/_govuk-elements.scss
public/sass/elements/_govuk-template-base.scss

This pull request removes any GOV.UK template-specific variables and mixins.
It aims to ensure that the govuk-elements-sass package can be used without govuk_template (so only the govuk_frontend_toolkit is a dependency).
The base partial is renamed to govuk-template-base.scss to make it clear where these styles have come from.
Variables used only by the GOV.UK template for header and footer colours, eg. $footer-background are removed. 
The `media-down(mobile)` mixin is swapped with `media(tablet)` for external links, [to match the template](https://github.com/alphagov/govuk_template/commit/86106bfb332ff5c0346b92310a4117daeb2d8c8d).
cc. @dsingleton, @robinwhittleton.

Copy base styles set by govuk template

---

public/javascripts/application.js
public/sass/elements/_helpers.scss

Rather than setting `display:none` and `display:block` using `show()`; and
`hide()`, add and remove the `.js-hidden` class.
[I think this was introduced by this change to the GOV.UK template](https://github.com/alphagov/govuk_template/commit/0b6684331ba0aac717dfe4dbe3a2743e2108e54f), which sets both display:none and visibility:hidden, and the visibility:hidden isn't removed when show and hide are used.
This fixes #197.
I've also removed .js-enabled .js-hidden from GOV.UK elements as this is defined in the template.
It is worth noting that #183 has a much better implementation of the JS for toggles.
cc. @robinwhittleton @edwardhorsford.

Fix toggled content

---

public/javascripts/application.js

This content is currently set to display:block or display:none using
toggle().
Instead use toggleClass to add or remove the `.js-hidden` class, this takes
advantage of `.js-enabled .js-hidden` set by the [govuk_template](https://github.com/alphagov/govuk_template/commit/0b6684331ba0aac717dfe4dbe3a2743e2108e54f) and fixes a bug where the content to be revealed currently isn’t shown, as the
.js-hidden class isn’t removed.
This should have been added in #198, but it appears only the fix for radio buttons was committed.

Fix toggled content shown when a checkbox is checked

---

public/sass/_govuk-elements.scss

This is only required when govuk_template isn’t being used, which isn’t
true for govuk_elements.
This undoes the change introduced in 7777182b1121b3fb4bdebb7f35a308fe1d91a17f.

Comment out the govuk-template-base partial

---

package.json

- Allow New Transport font stack to be overridden by apps using
$toolkit-font-stack and $toolkit-font-stack-tabular

Bump govuk frontend toolkit to 4.10.0

---

package.json

[# 0.17.1](https://raw.githubusercontent.com/alphagov/govuk_template/master/CHANGELOG.md)
- Reduce file size of template: removes HTML comments, `type` attributes on
scripts, and uses HTML5 charset declaration. #208
- Switch external link media query to be mobile first #205
- Sass file cleanups
- Replace old grid mixins with newer grid from frontend toolkit #134
- Remove duplicate grey variables #201

Bump govuk template to 0.17.1

---

README.md

Explain how to install the govuk-elements-sass package.
Explain how to use Gulp's `includePaths` setting to set the path to the files imported from the
govuk_frontend_toolkit and the govuk-elements-sass package.

Add an example using Gulp to compile the govuk-elements-sass files

---

.travis.yml
README.md

There are times when production http://govuk-elements.herokuapp.com is out of-date, as only the latest tagged version is deployed to Heroku.
Instead deploy what is on master to production and create a new app: govuk-elements-sass-release, to preview the govuk-elements-sass package. Deploy the most recent tagged version to this app.
This then means that I can deploy changes which include bumping the GOV.UK template, which will be reflected immediately on Heroku and since these changes don't affect the GOV.UK elements Sass package, there's no need to bump the version in order to deploy these changes. 
Also update the README and remove the link to the test app.

Create new app to preview govuk elements sass releases

---

Gruntfile.js
public/sass/elements/_buttons.scss
public/sass/elements/_icons.scss

Remove the icons subfolder.
These assets are now copied to `/public/images`, so the folder structure for
these assets is the same as that of the [govuk frontend toolkit's images folder](https://github.com/alphagov/govuk_frontend_toolkit/tree/master/images).
For the govuk-elements-rails gem, which uses the govuk_frontend_toolkit gem, the path to the image assets will be the same.
cc. @robinwhittleton @robmckinnon.

Don't copy the govuk frontend toolkit images to an icons subfolder

---

public/sass/_govuk-elements.scss
public/sass/elements/_details.scss
public/sass/elements/_shame.scss

This is a pretty hacky fix so I’ve tried to describe it as accurately as possible in the comments. It can be removed if either of the following happens:
* Mozilla fixes their summary arrow with `display: inline-block`
* Mozilla remove their support for `@-moz-document`
Fixes https://github.com/alphagov/govuk_elements/issues/221

Fix the summary arrow in recent Firefox

---

package.json

- Remove the GDS-Logo font-face definition
- Move the @viewport statements to govuk_template. If you
upgrade to this version of govuk_frontend_toolkit and you’re also using
govuk_template you’ll need to upgrade that to at least 0.17.2 to
maintain compatibility with desktop IE10 in snap mode.

Bump govuk frontend toolkit to 4.11.0

---

package.json

- Fix a bug with the skip-to-content link and iOS Voiceover
- Migrate @viewport statement from govuk_frontend_toolkit
https://raw.githubusercontent.com/alphagov/govuk_template/master/CHANGELOG.md

Bump the govuk template to 0.17.2

---

jenkins.sh

This is to make diffing master against  whatever the latest released version
of the package is. This allows us to easily see what has been committed to
master but not yet released in a consistent way, eg with a diff like:
https://github.com/alphagov/govuk_elements/compare/latest-release...master
This means we don't need to know the latest release is tag `v4.10.0` (for example)
This also lets us track un-released package changes in tools like the deploy-lag-radiator
(https://github.com/dsingleton/deploy-lag-radiator)

Use a branch as an alias of the latest release

---

public/sass/_govuk-elements.scss
public/sass/elements/_helpers.scss

Check to see if the `image-url` function exists
If `image-url` is not defined (if we are not in a Rails environment), set
a path to `/public/images`.
This will fix the issue where elements is overriding `$path` for the [govuk_elements_rails gem](https://github.com/alphagov/govuk_elements_rails). 
cc. @robinwhittleton @dsingleton.

Fix path for rails and node environments

---

package.json

This will bring in the updated button padding, will remove the
@font-face declaration for Helvetica, and remove the @viewport
declarations (they’re added back in to govuk_template in 0.17.2).

Bump the govuk frontend toolkit to 4.12.0

---

public/sass/elements/_buttons.scss

fixes #228 
This padding should be referenced in GOVUK Frontend Toolkits Button mixin. A separate PR for the toolkit will be submitted.

Remove padding from .button class

---

LICENSE.txt
package.json

This matches the license used by the govuk_frontend_toolkit_npm
package.json file.
https://github.com/alphagov/govuk_frontend_toolkit_npm/blob/master/packa
ge.json#L13
This fixes the following warning: `npm WARN govuk-elements-sass@1.1.4 No license field.`.

Add MIT license

---

public/sass/elements-page.scss
views/examples/example_date.html
views/examples/example_details_summary.html
views/examples/example_form_elements.html
views/examples/example_form_validation_multiple_questions.html
views/examples/example_form_validation_single_question_radio.html
views/examples/example_grid_layout.html
views/examples/example_icons.html
views/examples/example_radios_checkboxes.html
views/examples/example_typography.html
views/guide_alpha_beta.html
views/guide_buttons.html
views/guide_colour.html
views/guide_data.html
views/guide_errors.html
views/guide_form_elements.html
views/guide_icons_images.html
views/guide_layout.html
views/guide_typography.html
views/index.html

The GOV.UK template sets a skiplink to `#content` (just tab on any GOV.UK page and hit ENTER when "Skip to main content" is highlighted).
This allows users to navigate to the main content area using only the keyboard. Pressing enter when focus is on the skiplink should then set focus on the #content area.
In Safari, there's a bug where this doesn't happen unless `tabindex="-1"` is set on the destination element (in this case `<main id="content">`).
Here's the bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=37721 
This pull request adds:
- `tabindex="-1"` to the `<main>` element wherever it appears in a template
cc. @aduggin.

Add `tabindex-1` to fix the skiplink in Safari

---

public/sass/elements/_reset.scss

Firefox now supports text-decoration with a dotted underline; consequently (and inline with W3’s recommended default stylesheet) Mozilla updated Firefox’s default stylesheet to style abbrs and acronyms with a dotted text-decoration instead of a dotted border. Our reset stylesheet removes borders from abbr and acronym elements, but doesn’t reset text decoration. The upshot of all this is that every abbr on styled by govuk_elements now has dots underneath it.
This patch simply adds a rule to remove text-decoration from abbr and acronym elements. If text-decoration is being deliberately set anywhere it’ll override this base rule.

Remove abbr underlines in Firefox

---

public/sass/elements/_shame.scss

Disable the DuplicateProperty property linter in `_shame.scss`, to allow
the second property fall back to the first if not supported.
cc. @robinwhittleton.

Fix scss lint errors

---

Gruntfile.js
public/sass/elements/_reset.scss

When `grunt test` is run, run the lint task first to lint the sass
files.
Then test that the default task works.
This should fail and then pass once #243  is merged.

Make sure the test task fails if scss lint fails

---

views/guide_form_elements.html
views/snippets/form_inset_radios.html

This PR adds more information on how panels can be used and links the "toggled content" section (Conditionally revealing content), to the section in Typography, "Inset text".
1. panels can be used within forms to connect toggled or revealed
content with the question above (in form elements)
2. wide panels can be used to draw attention to important content on
the page (in typograpghy)
3. add a link from the toggled content section, to the inset text
section.
4. update the conditionally revealed content example to show the "how would you like to be contacted?" example.
This fixes #211 and #179.

Update guidance for toggled content

---

public/sass/elements/_forms.scss
public/sass/elements/_panels.scss
public/sass/elements/forms/_form-block-labels.scss
public/sass/elements/forms/_form-date.scss
public/sass/elements/forms/_form-validation.scss
views/examples/example_form_elements.html
views/snippets/form_date.html
views/snippets/form_radio_inline_yes_no.html

> This PR sets consistent spacing between form labels and controls (1.), removes additional spacing between block labels - the large hit area radio buttons and checkboxes (2.) and adds more examples to the Form elements example page (3).
------------
1. Set 10px spacing underneath form labels, form hint text and an error message, when it is shown (see screenshot for 3).
2. Remove the spacing underneath block labels when they are inline (screenshots below).
There is currently a 10px bottom margin, to set spacing between block labels.
The above screenshots shows extra spacing underneath the YES/NO question.
This bottom margin works well when they are stacked, but when they are inline - it should be removed.
There is also extra bottom spacing underneath the toggled content (seen under …

Consistent spacing underneath block labels and toggled content

---

public/sass/elements/_reset.scss

IE9-11 and Edge 12-13 can be completely fixed using box-sizing: border-box; max-width: 100%, but IE8 will still experience some issues as “the min-width property applies to content-box even if box-sizing is set to border-box” cite.
IE8-11 can be fixed using the 456 Berea St fix display: table; white-space: normal, but this fix will not work at all for Edge 12-13.

Fix legend text wrapping in IE.

---

views/snippets/form_hint_text.html

The example NI number doesn't [match the others used elsewhere](https://github.com/alphagov/govuk_elements/search?utf8=%E2%9C%93&q=VO+12+34+56+D).
Amend this example to be the same as the others.
This fixes #251.

Amend National Insurance number example to match other examples

---

app.js
package.json

This was [updated for the prototype kit in October 2015](https://github.com/alphagov/govuk_prototype_kit/pull/32).
This one is to be merged first. cc. @joelanman, @robinwhittleton.

Update GOV.UK elements to use Express 4

---

app/views/guide_typography.html

- Link to caniuse to show which browsers support the HTML5 details and summary elements
- Link to GOV.UK element's details summary polyfill JS
- Link to example page with details/summary test cases
This fixes #120.

Add an extra panel to describe how details summary is used

---

app/config.js
app/views/layout.html
app/views/layout_example.html
server.js

This pull request is another step towards getting the GOV.UK elements app to work in the same way as the prototype kit. 🎆 
Add a config file, ensure that server.js uses the config file, then define a cookieText variable and pass the cookieText variable to all views. 
Also add the missing blocks for the cookie message in both layout files.
Screenshot before (empty blue cookie banner at the top of the screen):
Screenshot after (cookie banner with text at the top of the screen):

Fix default text for global cookie message

---

public/sass/elements-page.scss
public/sass/elements/_layout.scss

Pressing enter when focus is on the skiplink sets focus on the #content
area, remove the blue outline which appears.
This was previously set in the elements-page stylesheet, so it wasn’t
being applied to all pages (this is the stylesheet for styling the page furniture and isn't included in the example pages).

Remove the outline from the main content area

---

package.json

The Jinja version of the GOV.UK template is now published to npm,
update package.json.

Use the govuk template jinja npm package.

---

app/views/examples/example_form_elements.html
app/views/snippets/form_file_upload.html

Use the button style to prompt for a file upload

---

package.json

- Make headings block-level by default (PR #200). If you are styling
elements you want to be inline with heading includes, you’ll need to
explicitly make them inline in your CSS.

Bump govuk frontend toolkit to 4.13.0

---

app/views/layout.html
app/views/layout_example.html

Create a new `body_start` block to insert the Google Tag Manager script
inside the body of the page.
This also fixes the validation errors caused by the Google Tag Manager
script being inserted in the head of the page, rather than in the body.

Move the Google Tag manager script

---

app/views/snippets/buttons_button_start_now.html

By keeping `role="button"` on start-button links:
1. JAWS announces "*Continue. Button. To activate press space bar*".
2. VoiceOver (Mac) via Chrome announces "*You are currently on a button. To click this button, press Control-Option-Space*".
Unfortunately:
* Pressing space does nothing in older versions of JAWS.
* Pressing Control-Option-Space does nothing in Chrome.
Why? A `keyup` event listener is still required to handle the space key. This will prevent some assistive-device users from starting the service.
I'd advise removing the `role` as this is probably a mistake.
Thanks

Remove button role from start link

---

.travis.yml
package.json

- Fix tabular number sizing in Firefox ([PR
#301](https://github.com/alphagov/govuk_frontend_toolkit/pull/301))
- Allow use of multiple GA customDimensionIndex. See [this
section](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/
docs/javascript.md#using-google-custom-dimensions-with-your-own-statisti
cal-model) of the documentation for more information.
- Configurable duration (in days) for AB Test cookie. See [this
section](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/
docs/javascript.md#multivariate-test-framework) of the documentation
for more information.
- Allow base scripts to run within a module loader. See [this
PR](https://github.com/alphagov/govuk_frontend_toolkit/pull/290) for
more information.

Bump govuk frontend toolkit to 4.14.1

---

jenkins.sh

Added in https://github.com/alphagov/govuk_elements/pull/232
The push failed in the most recent release/build:
```
To git@github.com:alphagov/govuk_elements.git
! [rejected]        master -> latest-release (non-fast-forward)
error: failed to push some refs to 'git@github.com:alphagov/govuk_elements.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
```
Given it's just for tracking, we can safely force push.

Force push latest release tracking branch

---

package.json

- Publish the Jinja version of the template to NPM
- Update HTML5 Shiv to the latest version
- Remove an errant font loader script that was only being used for IE8
https://raw.githubusercontent.com/alphagov/govuk_template/master/CHANGEL
OG.md

Bump govuk template to 0.18.0

---

package.json

Use version [4.15.0](https://github.com/alphagov/govuk_frontend_toolkit/commit/620c7fdb1eca75
cfb7a8c076cafcf50852a85008) of the GOV.UK frontend toolkit.
- Add support for Google Analytics fieldsObject
- anchor-buttons.js: normalise keyboard behaviour between buttons and
links with a button role

Bump govuk frontend toolkit to 4.15.0

---

package.json

https://github.com/alphagov/govuk_template/blob/master/CHANGELOG.md
- Remove gov.uk prefix from relative links when printing (PR #234)
- Fix a .visually-hidden bug on GOV.UK (PR #177)
cc @robinwhittleton

Bump govuk_template_jinja to 0.18.1

---

app/views/includes/scripts.html
public/javascripts/application.js

Include a script from the govuk frontend toolkit to shim anchors with
`role="button"` to be 'clicked' via the space key.
For context, here is the PR adding this script to the govuk_frontend_toolkit.
https://github.com/alphagov/govuk_frontend_toolkit/pull/310

Include the shim-links-with-button-role.js script from the frontend toolkit

---

public/sass/elements/_buttons.scss

Text on native input button/submit inputs is normally centred. When links are dressed as buttons the text is left aligned. This is okay on tablet views and above as buttons are only as wide as they need to be but on mobile views, buttons are full width. Centre the text for full width buttons for consistency.
Before:
After:

Centre text on full width buttons

---

app/views/examples/example_form_elements.html
app/views/snippets/form_inset_radios_show_errors.html
public/sass/elements/forms/_form-validation.scss

This PR adds two more examples to the form elements example page.
This fixes the issue with inputs using the `.form-control` class inheriting a red border, when a parent `.error` class is used.
Before:
After:
There is an example of this working here:
http://govuk-elements-test.herokuapp.com/form-elements/example-form-elements/#example-conditional-errors
cc. @trevorsaint, @gavboulton, @robinwhittleton. 
This fixes #249.

Form validation patterns for conditionally revealing content

---

.travis.yml
CONTRIBUTING.md
Gruntfile.js
README.md
app/config.js
app/routes.js
app/views/includes/scripts.html
app/views/snippets/form_error_radio.html
app/views/snippets/form_error_radio_show_errors.html
package.json
public/javascripts/application.js
public/javascripts/govuk/details.polyfill.js
public/javascripts/redirect.js
server.js
start.js

This PR updates GOV.UK elements to use [JavaScript Standard Style ](http://standardjs.com/). 
This work has [already been carried out for the GOV.UK prototype kit](https://github.com/alphagov/govuk_prototype_kit/pull/224):
[Standard](https://www.npmjs.com/package/standard) is an opinionated JavaScript linter that uses [eslint](http://eslint.org/) underneath and acts as a set of sensible defaults for it; [here are the most important rules](https://github.com/feross/standard#rules).
Ideally any shared JavaScript will be moved to the govuk_frontend_toolkit in the future.
TODO:
cc. @tvararu, @nickcolley.

Lint codebase using standard

---

public/sass/elements/_helpers.scss

The `!default` flag will only update the value of the variable when it has not been set. Adding this flag makes it easier to set when including elements modules in project specific files.

Add `!default` flag to image `$path`

---

app/views/guide_typography.html
public/sass/elements/_govuk-template-base.scss

We’d potentially like to remove external link styling, but first we want to see if anyone else has any input into whether they are useful or not. This adds a deprecation warning. I’ll also add a note to the changelog when we release the next version, and publicise it at that point.

Add a deprecation warning for external links

---

README.md
public/sass/elements/_helpers.scss
public/sass/main.scss

This PR fixes image paths for GOV.UK elements, which are currently broken.
Pull #285 added a `!default` flag to the $path variable, as `$path` is already set as `false !default` in url helpers, the file-url function fell through to use image-url. 
This resulted in broken images for GOV.UK elements.
I think the simplest solution here is to not try and define `$path` in the govuk-elements-sass files, instead this should be defined in the main.scss file for each project.
Moving the `$path` variable to main.scss for govuk elements fixes this. It will however, break background images for anyone using the govuk-elements-sass files, they will need to define $path for their own project.
Although it is a breaking change, I think it's a sensible one.
cc. @gavboulton can you let me know if this …

Remove the $path override from the helpers partial

---

app/views/guide_typography.html
app/views/snippets/typography_external_links.html
app/views/snippets/typography_links.html

This pull request fixes the layout of the "Links" section (see screenshot).
This pull request adds a new section for external links. This is to draw attention to external link styles, which have been deprecated. 
It uses the correct pattern to highlight information on a page and creates a new snippet for external links (so it is clear how these differ from links in body copy).
Before:
After:

Add a new section on external links

---

app/views/guide_form_elements.html
app/views/snippets/form_select_boxes.html

Add an example of a select box (drop-down list), this example been moved from the form examples page. 
Before:
After:

Add a select box example

---

app/views/guide_buttons.html

Before:
After:
This fixes https://github.com/alphagov/govuk_elements/issues/201

Add bullet points describing use of disabled buttons

---

app/views/examples/example_form_elements.html
app/views/guide_form_elements.html
app/views/snippets/form_file_upload_error.html

This PR fixes #298, by reverting the custom file upload style. 
The button style currently used prevents the button from gaining focus. 
This a bug, for now it is better to revert to the native file upload and in future find a custom solution which is accessible.
Before:
After:
After (focussed by tabbing through form examples page):
New section added to the "Form elements" guide:

Add new section for file upload, with examples

---

app/views/guide_form_elements.html

cc @joelanman.
- [x ] Bug fix (non-breaking change which fixes an issue)

Use 'not available', rather than 'disabled'

---

Procfile

start.js was removed in #306, instead use `npm start` to start the app.

Update Procile to use npm start

---

app/views/guide_form_elements.html

These were added to each of the examples as the selection-buttons.js
requires a parent form. Since then, the snippets have been modified so
they now show how they would work with a “one question per page” form
and also include a heading, then the parent form with a fieldset and
hidden legend for assistive technology.
The form elements wrapping these examples are no longer required, so
can be removed.

Remove wrapping form elements

---

public/sass/elements/_govuk-template-base.scss

It was not previously possible to fully override the font stack used with the GOV.UK template base.
It almost worked, as the font stack is usually pulled from the frontend toolkit, which [allows](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/mixins.md#changing-font) one to override it using a variable. However, the GOV.UK template base hardcodes the font used for unclassed elements to MTA Light, so if one sets the `$toolkit-font-stack` one ends up with a disconcerting mix of fonts.
This commit replaces the MTA Light reference to `$toolkit-font-stack`. Because GOV.UK Elements depends on the frontend toolkit, the latter variable is usually already initialised to MTA Light, so there shouldn't be any incompatibility issues. It also removes the now unused linter exception …

Inherit font stack from toolkit

---

Gruntfile.js
Procfile
package.json

This PR:
1. makes the grunt tasks less verbose and reorders them, to make them easier to read
2. removes the [Procfile](https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type) [*]
3. removes the dependency on grunt-shell and instead uses npm scripts
[*] _If no Procfile is present in the root directory of your app during the build process, your web process will be started by running `npm start`, specified in package.json._

Reorder grunt tasks, remove the Procfile, remove grunt-shell dependency

---

package.json

- Remove unnecessary print font fallback that causes regression
downstream ([PR
#328](https://github.com/alphagov/govuk_frontend_toolkit/pull/328))

Update the govuk_frontend_toolkit to 4.18.2

---

package.json

Logo fixes: Fix logo breaking layout when increasing font size, fix
invalid or non-standard CSS and remove obsolete CSS around logo, adjust
logo dimensions slightly (PR #237)

Bump govuk template to 0.18.3

---

.travis.yml
jenkins.sh
update-release-branch.sh

It is useful to have a branch showing the latest-release, get Travis to check the version.txt file and check out the most recent tag and then push a branch called "latest-release".
cc. @robinwhittleton.
This matches the work [already carried out for the govuk_prototype_kit](https://github.com/alphagov/govuk_prototype_kit/commit/000f078c3dbc2b5c8467122f655dc150cd74b618).

Get Travis to push a latest-release branch

---

public/sass/elements/_details.scss

When a details element follows a floated element its height consumes the height of the floated element. 
Clear floats for details elements so that details element height does not cover the previous floated element  (which matches panel styling).
Manual browser testing
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.

Clear floats on details elements

---

public/sass/elements/_elements-typography.scss

The [govuk_template defines the font-weight for `<strong>`](https://github.com/alphagov/govuk_template/blob/b6d4e882d195ed5093beb9fa1396438773c17de3/source/assets/stylesheets/_basic.scss#L141) elements to `font-weight: 600`.
Add a helper class `.bold` to override font-weight to 700.

Add a .bold helper class

---

README.md
public/sass/elements/_govuk-template-base.scss

[govuk_frontend_toolkit](https://github.com/alphagov/govuk_frontend_toolkit) is [potentially removing external link styles](https://github.com/alphagov/govuk_frontend_toolkit/pull/293). If that happens then we’ll want to remove them from govuk_elements as well.

Remove external link styles

---

package.json

Bump govuk_frontend_toolkit to 5.0.0 
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/CHANGELOG.md
This release includes two breaking changes:
- Removal of external link styles and icons, if you are using the external-link-* mixins you will need to remove them from your codebase  ([PR #293](https://github.com/alphagov/govuk_frontend_toolkit/pull/293))
- Correct spelling of the 'accordion' icon, you will need to check for the incorrect spelling 'accordian' and update if you are using this icon ([PR #345](https://github.com/alphagov/govuk_frontend_toolkit/pull/345))
And two minor changes:
- Amend GOVUK.StickAtTopWhenScrolling to resize the sticky element and shim when the .js-sticky-resize class is set ([PR #343](https://github.com/alphagov/govuk_frontend_toolkit/pull/343))
- …

Remove external links: bump govuk_frontend_toolkit to 5.0.0 and govuk_template to 0.19.0

---

app/views/guide_typography.html
app/views/snippets/typography_external_links.html

As we’re removing these from frontend toolkit we can remove the guidance around their use.

Remove guidance on external link icons

---

app/views/examples/example_form_elements.html
app/views/snippets/form_input_sizes.html

A designer was asking me about  different size lengths of an input box, and I couldn't find them shown as examples.
This pull requests add various examples using form-control classes
Added new html include snippets, I put them in order of % width
Manual browser testing

added example of input sizes using form-control classes

---

update-release-branch.sh

If it does, don't update the latest-release branch.
Otherwise, if the version number has changed - update the latest release branch.
This work was done for the [govuk_prototype_kit repo](https://github.com/alphagov/govuk_prototype_kit/pull/296), but hadn't been updated here.

Get Travis to check if the version number matches the tag number

---

app/views/examples/example_radios_checkboxes.html
app/views/snippets/form_checkboxes.html
app/views/snippets/form_inset_checkboxes.html
app/views/snippets/form_inset_radios.html
app/views/snippets/form_radio_buttons.html
app/views/snippets/form_radio_buttons_inline.html
app/views/snippets/form_radio_inline_yes_no.html
app/views/snippets/typography_legal_text.html

For consistency, update the `visuallyhidden` class to be hyphenated `visually-hidden` where it is used in code snippets.
We use hyphens between classnames everywhere else, let’s update the
examples to follow the same conventions.

Update visuallyhidden to be hyphenated

---

public/sass/vendor/prism.scss

This PR adjusts the colours used in example code blocks so that they are each 4.5:1 or greater contrast against the background. This will improve the readability for those who struggle with low contrast.
[Demo page](https://govuk-syntax-prototype.herokuapp.com/syntax2) with highlighting on many languages. username: syntax password: highlighting
* Adjust colours used for code elements to contrast compliant colours, using GOV.UK palette where possible (or tints thereof).
* Prioritises distinctive colours so that different elements can be distinguished.
* Makes the background lighter and adds a grey border to code examples. This matches other example styles used by elements, and helps distinguish the block now that the background is lighter.
* Lines of code wrap rather than overflowing.
* …

Update code example colours to improve contrast and readability

---

public/sass/elements/_forms.scss

This PR removes the rounded corners from form elements in iOS and also the inner shadow from form input elements and textareas.
This PR doesn't affect select boxes (drop-down lists) as we'd like to keep native styles for this element.
Before:
After:
Remove rounded corners for inputs and textarea elements using the
.form-control class.
Also set -webkit-appearance: none; to remove the inner shadow on these
elements.

Remove rounded corners on form inputs elements and textareas in iOS

---

app/views/guide_alpha_beta.html
app/views/guide_buttons.html
app/views/guide_colour.html
app/views/guide_data.html
app/views/guide_errors.html
app/views/guide_form_elements.html
app/views/guide_icons_images.html
app/views/guide_layout.html
app/views/guide_style_guide.html
app/views/guide_typography.html
app/views/includes/phase_banner_survey.html
app/views/index.html

Elements definitely isn’t in alpha any more (2.1.0 currently), and the page that the survey link points at was last updated 3 years ago. Let’s just drop it.
Fixes the symptom (but not the underlying problem) of https://github.com/alphagov/govuk_elements/issues/343

Remove the phase banner

---

package.json
public/sass/elements/_govuk-template-base.scss

Chrome and Safari’s focus ring differs from everyone else. This was reported in https://github.com/alphagov/govuk_elements/issues/324
Sets Chrome and Safari’s default `outline-offset: -2px` to be `0` to match other browsers.
Tested in Firefox, Chrome and Safari on elements locally. Original patch went through wider testing in govuk_template.
Screenshots in the original PR: https://github.com/alphagov/govuk_template/pull/259

Fix focus outline on form fields in Chrome / Safari

---

public/sass/elements/_panels.scss

This PR fixes #345.
This PR ensures that when two block labels are floated next to each other (using the `.inline` class on a parent fieldset) that any conditionally revealed content - for example a panel revealing an additional question, has a top margin of 10px.
For example, a yes/no question:
```
<fieldset class="inline">
<label class="block-label" data-target="the-revealed-panel">Yes</label>
<div class="panel-border-narrow" id="the-revealed-panel">
Additional content for "Yes" option
</div>
</fieldset>
```
Ensure that this panel has a top margin of 10px, so the border doesn’t
connect with the block label above it.

Fix the spacing underneath the "inline" block label example

---

app/views/guide_form_elements.html
app/views/snippets/form_inset_panel.html

This PR fixes the example in the [Radios and checkboxes section](http://govuk-elements.herokuapp.com/form-elements/#form-toggle-content), showing a grey left hand border on a conditionally revealed form field, the bug is that this example is empty.
Before:
After:
This PR:
- moves the code snippet for inset radios underneath the example
- adds a new snippet to show the inset panel example

Fix the grey left hand border example for Radios and checkboxes

---

app/views/snippets/data_48px_16px.html
app/views/snippets/data_48px_16px_example.html
app/views/snippets/data_80px_16px.html
app/views/snippets/data_80px_16px_example.html
public/sass/elements-page.scss
public/sass/elements/_elements-typography.scss

Amend [the data visualisation examples](http://govuk-elements.herokuapp.com/data/#data-visualisation), the styles for these were in the elements "style guide" stylesheets. Move the data styles to elements-typography.
Remove the headings and paragraphs within data examples, instead use `<span>`.
After screenshot:

Amend data visualisation examples

---

public/sass/elements/_forms.scss
public/sass/elements/_helpers.scss
public/sass/elements/forms/_form-block-labels.scss

This requires no change to the existing HTML: the custom inputs are built using pseudoelements. In a no-JS / no-CSS / IE8 scenario it falls back to standard inputs. To style the radio and checkboxes differently a class is needed on the label - this is automatically added by the new SelectionButton JS.
This is partially based on Verify’s styles, and updates a design by @timpaul and @joelanman inspired by observations from user research and lots of requests from @cjforms. The inputs are sized to match the height of text inputs.
Tested on:
- IE 7-11
- Edge 14
- OS X Firefox 48
- OS X Chrome 51
- OS X Safari 9
- iOS Safari 5.0 - 9.1  
- Android 4.4+ Chrome
Android Browser on BrowserStack’s Nexus 4 (4.2) is massively unresponsive and doesn’t seem to let you click on the radios most of the …

Custom radios / checkboxes

---

public/sass/elements/_forms.scss

This PR fixes #358.
Borders on form controls have been inadvertently changed  to`#00000`, this is too dark.
These should remain the same colour as the form label text.
As the color property isn't defined for `.form-control`, the user agent is setting this to `color: initial`, which is black #000000.
Setting `color:inherit` ensures the text inside a form control and the border colour become [$text-colour](http://govuk-elements.herokuapp.com/colour/#colour-sass-variables) `#0B0C0C`. 
Before:
After:

Set color:inherit to match text and border colour for form controls

---

package.json
public/sass/elements/_icons.scss

Update govuk_frontend_toolkit to 5.0.1
[# 5.0.1](https://raw.githubusercontent.com/alphagov/govuk_frontend_toolkit/master/CHANGELOG.md)
- Fix role="button" click shim ([PR #347](alphagov/govuk_frontend_toolkit#347))
- Make font variables lowercase ([PR#348](alphagov/govuk_frontend_toolkit#348))

Bump govuk_frontend_toolkit to 5.0.1

---

app/views/guide_alpha_beta.html
app/views/includes/phase_banner.html
app/views/snippets/phase_banner_alpha.html
app/views/snippets/phase_banner_beta.html
package.json
public/sass/elements/_phase-banner.scss

This PR anticipates the changes to the [govuk_frontend_toolkit](https://github.com/alphagov/govuk_frontend_toolkit/pull/353), by removing the state passed to the phase banner mixin.  This is no longer required, as the phase tag has a $govuk-blue background.
Once the govuk_frontend_toolkit has been updated, govuk_elements can be updated to use the latest version.

Update the phase banner examples, the phase tag is now $govuk-blue

---

app/views/snippets/form_error_multiple.html
app/views/snippets/form_error_multiple_show_errors.html
app/views/snippets/form_hint_text.html

Use the [example National Insurance number recommended by the service manual](
https://www.gov.uk/service-manual/user-centred-design/resources/patterns/national-insurance-number.html).
Also update the hint text when asking for a national insurance number so
the examples are consistent.
cc. @edwardhorsford.

Use the same example NI number throughout

---

README.md
app/views/examples/example_details_summary.html
app/views/examples/example_grid_layout.html
app/views/examples/example_radios_checkboxes.html
app/views/guide_buttons.html
app/views/guide_colour.html
app/views/guide_data.html
app/views/guide_form_elements.html
app/views/guide_icons_images.html
app/views/guide_typography.html
app/views/snippets/form_error_multiple.html
app/views/snippets/form_error_multiple_show_errors.html
app/views/snippets/form_hint_text.html

> “Smart quotes,” the correct quotation marks and apostrophes, are
curly or sloped. "Dumb quotes," or straight quotes, are a vestigial
constraint from typewriters when using one key for two different marks
helped save space on a keyboard.
– http://smartquotesforsmartpeople.com
***
http://smartquotesforsmartpeople.com/
Spotted by @quis' [over on Design Principles](https://github.com/alphagov/design-principles/pull/276), updating GOV.UK elements for consistency.

Use smart quotes and apostrophes

---

app/views/includes/propositional_navigation.html
app/views/includes/service_manual_navigation.html

Now that the new service manual is live, this page doesn’t exist any more.
Fixes https://github.com/alphagov/govuk_elements/issues/378

Fix the service manual link in the header

---

.travis.yml

The `before_install` section is run before each deployment. As this project has many deployments, the commands will be run multiple times. They're not idempotent so this fails:
```
fatal: remote origin_ssh already exists.
```
We can work around this by doing them as part of the test setup instead.

Move deployment setup to `before_install`

---

public/javascripts/redirect.js

We're missing a typeof in our conditional to check if something needs to be redirected.

Fix conditional match to use typeof

---

app/config.js

It’s unnecessary and doesn’t give an accessibility benefit. Thanks to @trevorsaint for catching this.

Remove the title from the cookie message link

---

.travis.yml

People can make pull requests from forks, which will try to decrypt
encrypted files using `$encrypted_85ebe8034b89_key` and `$encrypted_85ebe8034b89_iv`.
Travis doesn't make those environment variables available to forks
because then somebody could run `echo $encrypted_85ebe8034b89_key`
to get the value of the variable and get access to our secrets.

Only attempt to decrypt encrypted files on master

---

app/views/guide_colour.html

Remove swatches for alpha, beta, discovery and live.
Add context for the two status colour swatches - one is for alpha and
beta banners, the other for error messages.

Update status swatches

---

package.json

6.0 is the LTS version, update package.json to use this.

Update advisory node requirement to 6.0

---

public/sass/elements/_forms.scss

When overwriting colours via browser settings, Firefox and IE always default to black text in form fields, irrespective of said settings.
When the background of the form fields is transparent and the general background is dark (e.g. black), it results in black text on a black background, i.e. making the text invisible and therefore completely inaccessible.
It seems counterintuitive but due to browser bugs (which I will report) it is necessary to remove the `background-color: transparent`. The only downside I can see is that anyone wanting to use input fields on a non-white background would need to give it a background colour (which would actually re-introduce this bug again in Firefox).
A reduced test case to play around with: http://jsbin.com/sibube
See also …

Fix invisible input content when changing colours

---

public/sass/elements/forms/_form-block-labels.scss

This PR is copied from #399 by @miaallers.
It makes checkbox and radio focused styles visually consistent with the input focus style.
Closing #399 in favour of this PR, this one fixes the whitespace issues I wasn't able to update on Mia's fork.

Update custom radio and checkbox focus styles

---

app/views/guide_form_elements.html
app/views/snippets/form_checkbox.html
app/views/snippets/form_checkbox_native.html
public/sass/elements/_forms.scss

This fixes #335.
- Rename the snippet
- Updates the example to use a custom checkbox
- Remove the text about large hit areas, as this is contradictory

Update example of a single checkbox to use the new style

---

.travis.yml

With other GDS FE repos, see:
https://github.com/alphagov/govuk_frontend_toolkit/pull/385
Steps specified in before_deploy are only run if a deployment is
triggered [1], which will only happen on master, which can't be
done by a user without write perms.
[1] [Travis before_deploy documentation](https://docs.travis-ci.com/user/deployment/npm/#Running-commands-before-and-after-deploy)

Make Travis deployment config consistent

---

package.json

Update the govuk_frontend toolkit to the latest version.
This includes the following changes:
**5.1.1**
- Update the alpha, beta and discovery colours to $govuk-blue to match
the updated phase banner ([PR #370](https://github.com/alphagov/govuk_frontend_toolkit/pull/370))
- Fix radio button show/hide behaviour when used outside a form ([PR #375](https://github.com/alphagov/govuk_frontend_toolkit/pull/375))
- Fix a "Stick at top when scrolling" component bug related to scroll
anchoring in Chrome 56+ ([PR #376](https://github.com/alphagov/govuk_frontend_toolkit/pull/376))
- Minor travis fixes ([PR #373](https://github.com/alphagov/govuk_frontend_toolkit/pull/373))
**5.1.0**
- Allow custom options when tracking events ([PR #365](https://github.com/alphagov/govuk_frontend_toolkit/pull/365)) …

Bump govuk_frontend_toolkit to 5.1.1

---

.travis.yml

Use this new app - govuk-elements-review (previously, govuk-elements-test), rather than production (govuk-elements), as the app to build review apps from. 
This is so that we can make use of [Heroku's Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) to preview pull requests.

Update travis to deploy to a new app for review

---

.travis.yml

This was broken in #408, where the setup was moved to `before_deploy`
to avoid permission issues when running PR tests in a way consistent
with other `alphagov` apps.
Previously that was guarded by a shell if, which was removed, but a
bit at the end was left and is breaking deployment builds. :(
- Fixes deployment builds.
Internal change, no effect on semver.

Fix broken travis deployment setup

---

.travis.yml

This PR attempts to fix deployment to Heroku, which is currently failing.
This reverts the changes made in #404:
https://github.com/alphagov/govuk_elements/pull/408
It moves the open_ssl command back to before_install, otherwise it runs more than once (as
there is more than one deploy provider).
See related issue here:
https://github.com/travis-ci/travis-ci/issues/2570

Revert Make Travis deployment config consistent

---

app/views/includes/breadcrumb.html

This PR updates the breadcrumbs to use the aria-current attribute as described here:
http://tink.uk/using-the-aria-current-attribute/.
Fixes #412.

Add an aria-current attribute to the breadcrumbs

---

app/views/examples/example_form_elements.html
app/views/examples/example_radios_checkboxes.html
app/views/includes/scripts.html
app/views/snippets/form_checkbox.html
app/views/snippets/form_checkboxes.html
app/views/snippets/form_error_radio.html
app/views/snippets/form_error_radio_show_errors.html
app/views/snippets/form_inset_checkboxes.html
app/views/snippets/form_inset_radios.html
app/views/snippets/form_inset_radios_show_errors.html
app/views/snippets/form_radio_buttons.html
app/views/snippets/form_radio_buttons_inline.html
app/views/snippets/form_radio_inline_yes_no.html
public/javascripts/application.js
public/sass/_govuk-elements.scss
public/sass/elements/forms/_form-block-labels.scss
public/sass/elements/forms/_form-multiple-choice.scss

This PR removes the [JavaScript requirement](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/selection-buttons.js) for radio buttons and checkboxes. To do this the markup had been changed, but there are no visual changes for users (beyond IE < 9 having a focus box around just the input rather than the whole label).
The new radios and checkboxes still required the selection buttons JS. This is a potential point of failure that’s a hangover from the old grey-box implementation, and isn’t really needed. We originally went with it because removing it would require markup changes and would mean that it they weren’t a drop-in solution. I think that was probably a mistake though, so this corrects it.
While making the markup changes I took the opportunity to …

Radios and checkboxes without JS

---

app/views/examples/example_date.html
app/views/examples/example_form_elements.html
app/views/snippets/form_date_show_errors.html
app/views/snippets/form_error_multiple.html
app/views/snippets/form_error_multiple_show_errors.html
app/views/snippets/form_error_radio.html
app/views/snippets/form_error_radio_show_errors.html
app/views/snippets/form_file_upload_error.html
app/views/snippets/form_inset_radios_show_errors.html
public/sass/elements/forms/_form-validation.scss

The styling for form validation is pretty fragile and relies on a parent `.error` selector to apply a red border to the left of a `.form-group` div. This class also sets a red border on any `.form-control` inputs that are direct descendents. 
Rather than relying on a child div sitting inside a parent for this to work - add two new classes `.form-group-error` and `.form-control-error`. One will set the border for form-groups and the other for inputs/textareas with a class of form-control.
This also solves the problem where there may be multiple `.form-control` elements within a parent `.error` - and only one of them needs to have a red border - an example of this is the date of birth pattern.
> This would be a breaking change, but at some point we'll need to make breaking changes, so let's …

Breaking changes to form validation

---

public/sass/elements/_tables.scss

Fixes #403 - Tables have inconsistent front sizes.
Remove the core-16 mixin being applied to table cells with a class of
numeric. All tables should use 19px - to match the body text size.
Tested by running the GOV.UK elements app locally, see screenshots, or Heroku app preview.

Ensure that table cells using tabular-numbers are 19px

---

package.json

This updates show-hide-content.js and fixes the current issue for “Conditionally revealed content” where the toggled content areas aren’t shown.
From the GOV.UK Frontend Toolkit changelog:
- Update show-hide-content.js to work with new `.multiple-choice` custom radio buttons and checkboxes, released in GOV.UK elements 3.0.0 ([PR #390](https://github.com/alphagov/govuk_frontend_toolkit/pull/390))
- Fix buttons not having an outer edge when colours are changed via browser settings - add an outline so they look like buttons. ([PR #377](https://github.com/alphagov/govuk_frontend_toolkit/pull/377))

Update the govuk frontend toolkit to 5.1.2

---

update-release-branch.sh

Remove git config as this already exists (in the first script provider)
Force push the latest-release branch to origin_ssh (this is also used
by push-version-tag to update the tag).

Simplify the latest-release script

---

create-release.sh

This PR updates govuk_elements to match the govuk_frontend_toolkit's `create-release.sh` script:
- splits the openssl command onto two lines
- uses an environment variable for the repo name
- adds missing comments for the latest-release branch

Make create-release.sh consistent with FET

---

app/views/examples/example_radios_checkboxes.html

[example_radios_checkboxes.html](https://github.com/alphagov/govuk_elements/blob/a06c8ec857c3b84e0d7da6c6ea734b8dcb45dd29/app/views/examples/example_radios_checkboxes.html) has markup that was broken in the the [radio button update](https://github.com/alphagov/govuk_elements/commit/4fb688e208fb65a04d5ccde59700ee4d73c39b7d). This updates it to match the correct multiple-choice markup.
Fixes https://github.com/alphagov/govuk_elements/issues/436.

Fix example of radio markup

---

public/sass/elements/forms/_form-multiple-choice.scss

On the new radio buttons / checkboxes, there is a 12px gap between the input control and the label which has a hand cursor (inherited from the `.multiple-choice` parent div) but is not clickable. Since it has the hand cursor, I feel it _should_ be clickable.
The alternative would be to not show the hand cursor in this 12px dead area but that doesn't feel right to me?
Checked in Chrome (Ubuntu), IE8, IE9, IE10, IE11, Edge 14, iOS9 Safari, Android 6 Chrome.
Can test more if necessary, if this change is approved. Just let me know...

Resolve 'dead area' between radio/checkbox and label that has hand cursor but is not clickable

---

app/views/examples/example_radios_checkboxes.html

Closes #442.
Has the added effect of providing more information to users of assistive technology, which seems desirable. I tested in VoiceOver and the behaviour is that the bold part of the label gets pronounced, followed by a short pause, followed by the rest of it, which is ok.
I have not looked to see if this problem exists in other places. [Digging here might uncover more places](https://github.com/alphagov/govuk_elements/commit/4fb688e208fb65a04d5ccde59700ee4d73c39b7d).

Fix poor alignment of text in radios example

---

app/views/examples/example_details_summary.html

This was moved into a govuk/ folder, update the example page to reflect
this.

Update broken link to the details polyfill

---

public/javascripts/govuk/details.polyfill.js

As reported in #130, the details/summary cannot be opened when using JAWS or NVDA in Internet Explorer.
As part of my investigation I also found that using the enter key on the summary would also submit a form in IE if details is used within a form.
This fixes both issues.
Some screen readers map the screen reader key + space (or enter) to the **click** event. As you can see in [Event Handlers and Screen Readers](http://unobfuscated.blogspot.co.uk/2013/05/event-handlers-and-screen-readers.html), the click event is usually the **only** event fired for IE and JAWS/NVDA combinations.
Our polyfill is currently listening for the keyup, keypress and mouseup events. It used to listen to the click instead of the mouseup event, but that was [changed because it made it trigger twice in …

Fix details polyfill for JAWS and NVDA in IE

---

app/views/examples/example_radios_checkboxes.html
package.json

Update govuk_elements to use the most recent version of govuk_frontend_toolkit.
Also remove any remaining references to selection-buttons.js (which was removed from this repo in #406), selection-buttons.js was deprecated in govuk_frontend_toolkit 5.2.0.
- New feature (non-breaking change which adds functionality)

Bump govuk_frontend_toolkit to 5.2.0

---

package.json
yarn.lock

It looks like there is a node_modules cache issue with Heroku when
using Yarn.
Attempting to fix by updating node-sass to version 4.5.2.
This commit has been deployed to Heroku manually and the app is running here:
http://govuk-elements.herokuapp.com/

Update node-sass to fix Heroku

---

package.json

Move the dependencies to run the govuk-elements app into
devDependencies.
Ensure that the dependencies for the govuk-elements-sass package are in
dependencies.
This reverts the [change made on Friday](https://github.com/alphagov/govuk_elements/commit/ff665369c81f8891b5dd99613507a1b5f7c4e8f4), when trying to debug the node_modules cache issue with Yarn and Heroku: https://github.com/yarnpkg/yarn/issues/1981
For this to work on Heroku, production mode will need to be disabled.

Revert changes to dependencies and devDependencies

---

package.json

Reverts alphagov/govuk_elements#448.
This breaks deployment to Heroku.

Revert "Revert changes to dependencies and devDependencies"

---

app/views/snippets/form_inset_panel.html

This example is a smaller part of another example on the same page,
hence the IDs were duplicated.
The ID on the panel isn't relevant for this standalone example and the values of the for, id and name attributes have been updated to use an id that isn't already in use on the page.

Remove duplicate IDs from inset panel example

---

app/views/guide_colour.html
public/sass/elements/_components.scss

Increase the heading size by one level and use large text (36px) for
the text which is currently failing contrast checks.
For smaller screens, the font-size (of the large text - as [we're using the govuk_frontend_toolkit's core-36 mixin](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss#L73)) will be 24px.
Discussion over in #200.
- Bug fix (non-breaking change which fixes an issue) Fixes #200.

Increase the size of the text in the highlight box

---

public/sass/elements/_forms.scss

Accessibility fix on Windows 10 IE and Edge select box active 
Issue : https://trello.com/c/LGKKreic/461-tech-spike-insufficient-colour-contrast-of-select-box-items
Tested on IE11 and Edge 15 where the issue existed.
Also tested on latest Chrome. Firefox and Safari to make sure nothing was affected there. 

Windows10 select box contrast ratio in IE and Edge

---

app/views/examples/example_typography.html
app/views/guide_typography.html
app/views/snippets/typography_lists.html

Numbered lists should be written as sentences (start with a capital, end with a full stop).
This is confirmed in https://www.gov.uk/guidance/how-to-publish-on-gov-uk/markdown#numbered-list 
and
http://govspeak-guide.herokuapp.com/#lists-of-steps

Corrected numbered list rules

---

app/views/snippets/form_focus.html
app/views/snippets/form_hint_text.html
app/views/snippets/form_input_sizes.html
app/views/snippets/form_labels.html
app/views/snippets/form_select_boxes.html

Add `name` attributes to form fields in snippets.
Makes the snippets more complete for when users are copying and pasting.
This is particularly helpful for users of the prototype kit. It's easier for us to tell users to change the value of the `name` attribute than it is to tell them to add one from scratch.
Has not been tested
I don't think this requires any updates to the documentation.

Add name attributes to form fields

---

.gitignore
Gruntfile.js
app/views/guide_alpha_beta.html
app/views/guide_buttons.html
app/views/guide_data.html
app/views/guide_errors.html
app/views/guide_form_elements.html
app/views/guide_icons_images.html
app/views/guide_layout.html
app/views/guide_typography.html

This PR removes the Grunt tasks to encode the HTML snippets, updates the paths to each of the snippets and wraps each code example snippet in an escape filter. 
This ensures the HTML inside a code example is escaped when the
snippet is rendered, so when JavaScript is disabled, the code snippets
remain visible.
Originally suggested by @selfthinker in #453, this fixes #453. To clarify, the snippets folder is 
still necessary, but not the `snippets/encoded` folder.

Replace encoded snippets with escape filter

---

app/views/examples/example_date.html
app/views/examples/example_form_elements.html
app/views/examples/example_form_validation_multiple_questions.html
app/views/examples/example_form_validation_single_question_radio.html
app/views/snippets/form_date.html
app/views/snippets/form_date_show_errors.html
app/views/snippets/form_error_multiple.html
app/views/snippets/form_error_multiple_show_errors.html

The `aria-describedby` attribute was added before we moved the error message or hint text for a field into its label (or legend in case of radio/checkboxes) in 87449f013521d09ca2b51df113f4c85c85ec36d8.
Now that it's also in the label/legend, it gets read out multiple times to screen readers. Therefore it is not necessary anymore and should be removed.
The error message and/or hint text is read out twice to screen readers. Example pages where that happens:
* http://govuk-elements.herokuapp.com/errors/example-form-validation-multiple-questions
* http://govuk-elements.herokuapp.com/form-elements/example-date/
I tested with JAWS in IE 11, NVDA in Firefox and VoiceOver in Safari.
They all behave the same when tabbing to the input field. Before they were reading the additional text twice and …

Remove `aria-describedby` from erroring form fields and hint text

---

package.json

- Increase button focus specificity to avoid being overridden by
govuk_template
- Fix a Javascript error in IE7 caused by trying to access a character
within a string using array notation
- Breaking change: configure the GOV.UK Analytics tracker with
`govukTrackerUrl` instead of `govukTrackerGifUrl`
- Fix the sending of the GA Client ID with calls to the GOV.UK Tracker
- Disable GA ad tracking

Bump govuk_frontend_toolkit to 6.0.2

---

.travis.yml
package.json
packages/govuk-elements-sass/package.json

This PR fixes releases to npm and GitHub.
For npm, `skip_cleanup: true` must be set to prevent Travis cleaning up files after the build has completed.
The failing build can be seen here:
https://travis-ci.org/alphagov/govuk_elements/builds/233672682#L1104
For GitHub, an encrypted OAuth token has been added to enable automatic releases using GitHub.
This fixes the bad credentials error here:
https://travis-ci.org/alphagov/govuk_elements/builds/233672682#L1150
The author field is added to both package.json files, for consistency with our other [frontend repos](https://github.com/alphagov/govuk_frontend_toolkit_npm/blob/master/package.json).
Fixes #472.

Fix releases to npm and GitHub

---

app/views/guide_form_elements.html
app/views/snippets/form_textarea.html
assets/sass/elements/_forms.scss

Move the textarea snippet from the form example page into its own snippet. 
Show this example on the form elements page. 
Fixes #458.
- My change requires a change to the documentation.

Add a textarea example to the form elements page

---

app/views/snippets/form_error_multiple_show_errors.html
app/views/snippets/form_error_radio_show_errors.html

Add grid and column wrappers to constrain summary boxes. These are now
2/3 of the width of the page.
Fixes #356.

Constrain width of validation summary boxes to 2/3

---

app/views/guide_colour.html

Add guidance on the minimum font size to be used for white text on a turquoise background.

Add guidance on font size for confirmation page

---

assets/sass/elements/_tables.scss

Remove right padding from last table cells.
I also removed the `color` declaration as it isn't necessary.
This is a design-y problem. Can a designer please fill this section in and explain what the problem is? @edwardhorsford raised it.
Ed: it makes things look neater, and matches the padding (or lack thereof) used on the other side.
I'm not 100% sure if it's a breaking change? If it is, it's only breaking things minimally.

Fix table spacing

---

app/views/snippets/data_table.html
app/views/snippets/data_table_numeric.html
assets/sass/elements/_tables.scss

The table examples on http://govuk-elements.herokuapp.com/data/ have some semantic and therefore accessibility issues.
1. The "numeric tabular data" table should have the first column marked up as row headings (`th`). When I tried that, it didn't look right because there was too much bold. Adding more styling to remove that depending on types of tables would open a whole new can of worms, so I opted to change the content of the table instead. That should also make the table clearer out of context. (The data for that table was taken from https://www.gov.uk/vehicle-tax-rate-tables/other-vehicle-tax-rates)
2. The "data in a table" table uses `thead` wrongly. I moved that into a `caption` instead. And as we didn't have any styling for captions yet, I've added that as well. Hopefully this will …

Fix table semantics

---

app/views/examples/example_radios_checkboxes.html
app/views/guide_form_elements.html
app/views/snippets/form_checkboxes.html
app/views/snippets/form_inset_checkboxes.html
assets/sass/elements/_elements-typography.scss
assets/sass/elements/_forms.scss

This is an alternative solution to #485.
Most groups of checkboxes and radio buttons within Elements have an additional introductory help text which isn't a hint. It's usually there to help less technical people understand that you can select multiple checkboxes, but can also be used for other purposes.
This moves that text into the legend to also make it accessible to assistive technologies like screen readers. The styling is nearly the same as before and adds a class to the current paragraph declaration to re-use its styling.
There is a bit more spacing above the help text in the new version (probably `0.26316em` which translates to 5px with default settings), even though it uses the same CSS. That is because previously the margins were collapsing as the `p` came directly after the `h3` …

Move form help text into legend

---

package.json

- Fix invalid html from Apple touch icons syntax [PR #300](https://github.com/alphagov/govuk_template/pull/300) and
update icon sizes to match Apple specs

fix(package): update govuk_template_jinja to version 0.20.1

---

package.json

0.22.0
- Adds new Apple touch icons to precompile list for Rails apps [PR #305](https://github.com/alphagov/govuk_template/pull/305)

fix(package): update govuk_template_jinja to version 0.22.0

---

assets/sass/_elements.scss
assets/sass/_govuk-elements.scss
assets/sass/_govuk-toolkit.scss
gulpfile.js
packages/govuk-elements-sass/package.json

Move the import of the govuk-elements styles into a single, standalone file so they can be imported as a single import statement without also including govuk_frontent_toolkit files.
We use a sass compiler which is npm-aware (https://npmjs.com/npm-sass), and so generally don't use configured `includePaths` when compiling. However, the main sass file in this repo is only compilable if the `includePaths` are set.
By moving the govuk-elements-sass code (as distinct from the govuk_frontend_toolkit code), we can `@import "govuk-elements-sass"` in our stylesheets and have them compile correctly (note the `sass` property added to package.json supports this shorthand, as opposed to having to specify a full file path)
This will also support any users who wish to import the elements code alone, …

Allow for a single-file import of all elements stylesheets

---

create-release.sh

Amend the username and email to use the details for the GOV.UK Patterns & Tools CI User, in the create-release.sh script.

Release as “GOV.UK Patterns & Tools CI User”

---

app/views/guide_alpha_beta.html
app/views/guide_buttons.html
app/views/guide_colour.html
app/views/guide_data.html
app/views/guide_errors.html
app/views/guide_form_elements.html
app/views/guide_icons_images.html
app/views/guide_layout.html
app/views/guide_typography.html
app/views/index.html
app/views/layout.html
assets/sass/elements-documentation.scss

This allows users to skip directly to the page content, avoiding the repetition of the breadcrumb on each page.
The `<main>` tag is wrapped with a containing div `site-wrapper`, to establish a central column.
The breadcrumb is a child of the site-wrapper container. 
The `<main>` element starts after the breadcrumb. 
GOV.UK currently has the breadcrumb inside the `<main>` element, ideally, the two should be consistent.
Fixes #343.

Move breadcrumb outside the main element

---

assets/sass/elements/_forms.scss

Removes float and width 100%, for `.form-group`, `.form-section`, `.form-block`.
Fixes #257.
Bug fix (non-breaking change which fixes an issue)
I have read the **CONTRIBUTING** document.

Remove float and width 100% from form group

---

assets/sass/elements/_panels.scss

The margin above the last item is too large, as seen in the image below.
Fixes #428.
Bug fix (non-breaking change which fixes an issue)
I have read the **CONTRIBUTING** document.

Fix spacing above nested panels

---

app/views/index.html

Replace the link mentioning the "Hackpad" to the index page of GOV.UK Design Patterns.
cc. @timpaul.

Update link to GOV.UK Design Patterns

---

app/views/guide_typography.html

Fix a broken link on the typography page where it linked to a polyfill that had been moved.

fix broken link to polyfill

---

.travis.yml

Publishing to npm is currently failing for this repo, replace the encrypted api key with one for the alphagov user. 
Encrypt and add api key to .travis.yml by running:
travis encrypt --add deploy.api_key <apikey>.

Update the encrypted api key for npm

---

.travis.yml

Move tests into their own build stage. It appears the script to run the
tests is being ignored without this.
This can be seen working here:
https://travis-ci.org/alphagov/govuk_elements/builds/234778197#L217
and then no longer working here:
https://travis-ci.org/alphagov/govuk_elements/builds/246248025
After 938689db433c1cadfc1a93a2ac0ce28e8f0f62f8 was merged.

Ensure Travis runs tests

---

assets/sass/elements/_tables.scss

Having (row) headers is very important for accessibility.
But all of our table headers are bold, and that often doesn't look good with long row headers.
People who understand table semantics would need to overwrite that.
And people who don't understand semantics might choose not to use them.
We often have badly formatted tables. One reason for that is how govspeak works (I will raise an issue for that later). I suspect that another reason is that when you format a table correctly, it often doesn't look good. (But I don't have any evidence to back that up.)
E.g. if you formatted the tables on our [bank holiday page](https://www.gov.uk/bank-holidays) correctly, it would currently look like this:
(Although that doesn't use Elements but the example would be the same with Elements.)
And …

Only make column headers bold, not row headers

---

app/views/examples/example_form_elements.html
app/views/examples/example_radios_checkboxes.html
app/views/snippets/form_checkboxes.html
app/views/snippets/form_inset_checkboxes.html
app/views/snippets/form_inset_radios.html
app/views/snippets/form_radio_buttons.html
app/views/snippets/form_radio_buttons_inline.html
app/views/snippets/form_radio_inline_yes_no.html

When we have one thing per page, our current pattern is to let the h1 be the question and then repeat but visually hide it in the legend (or label). That means screen readers will read the question twice, which is not a proper barrier but annoying and gets raised as an issue again and again, e.g. in #320 or [on the cross-government accessibility mailinglist](https://groups.google.com/a/digital.cabinet-office.gov.uk/forum/#!searchin/accessibility-community/error$20summary$20heading%7Csort:relevance/accessibility-community/oekFWa1LhdE/n2-pwcTHAQAJ).
This changes that by **moving the h1 into the legend**. That creates the following issues:
* It is currently invalid. But it will be valid in [HTML 5.2](https://www.w3.org/TR/html52/sec-forms.html#the-legend-element) and the W3C validator passes …

De-duplicate legends/headings

---

packages/govuk-elements-sass/README.md

When using the guidance for 'packages/govuk-elements-sass', the README.md file (changed in this pull request) directs to use 'npm install govuk-frontend-toolkit' command however the correct name for the npm package is 'govuk_frontend_toolkit' (just changing hyphens for underscores).
Single change to README.md file therefore no tests executed.
- I have read the **CONTRIBUTING** document. - Apologies though, wasn't sure if this actually needed a new version given that it's a minor, non-functional change.

Update govuk-frontent-toolkit name to match npm package naming

---

app/views/guide_form_elements.html
app/views/snippets/form_checkboxes_disabled.html
app/views/snippets/form_radio_buttons_disabled.html
assets/sass/elements/forms/_form-multiple-choice.scss

Fixes #517.
Adds cursor:default for both the disabled input and the label - for radio buttons and checkboxes.
Also adds examples of each.
Radio button:
Checkbox:

Set cursor:default for disabled radio buttons and checkboxes

---

packages/govuk-elements-sass/public/sass/elements/forms/_form-multiple-choice.scss

IE sometimes miscalculates the border width of a rotated element resulting in a thin border as shown in #518. Setting a transparent border will fix the issue without affecting semantics or rendering on any other browser.
Tester with BrowserStack: IE10, IE11 on Windows 7
Before
After

Fix #518: stray line on checkbox on IE11

---

assets/javascripts/govuk/details.polyfill.js
packages/govuk-elements-sass/public/sass/elements/forms/_form-multiple-choice.scss

The details.polyfill.js script expected `<details>` to contain a `<summary>` and a `<div>` representing the content. If this structure didn't exists the script crashes with a hard error as shown in #502.
As the `<details>` component can be potentially used in other scenarios across the page, if the structure is not followed, the polyfill script will not be executed.
Tested locally: Latest Safari, Firefox and Chrome on Mac
Tester with BrowserStack: IE11 and Edge15 on Windows.

Fix 502: Hard error in details.polyfill.js

---

CONTRIBUTING.md

🎉 
There was a typo.
Used my knowledge of the English language to verify that the insertion of a 'b' fixed the typo.
- My change literally is a change to the documentation.

Fix a typo in release docs

---

package.json

The postinstall script is causing the [npm release of govuk-elements-sass to fail](
https://travis-ci.org/alphagov/govuk_elements/jobs/253564908#L384).
Since [this script was added](https://github.com/alphagov/govuk_elements/commit/8a8867a281c2bfb9a5583b97eb6f1b9ab5e96a39) to build assets for Heroku, instead use
a [Heroku-specific build step](https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps).
Replace `postinstall` with `heroku-postbuild`, which runs after Heroku installs dependencies.

Replace postinstall script with Heroku's postbuild script

---

app/views/snippets/form_error_multiple.html
app/views/snippets/form_error_multiple_show_errors.html
app/views/snippets/form_error_radio.html
app/views/snippets/form_error_radio_show_errors.html

When there is an error in a form after submit, we show an error summary box above the h1. And the heading of that box is also an h1, making that two h1s per page.
The question why that is comes up again and again. For example, the accessibility audits by DAC (which a lot of departments are using) always raise that as an issue. And it was discussed a lot when it was first introduced in #71 (and previous PRs) and on various mailinglists.
As no visuals are affected, the main thing to look at is how screen reader users react to different heading levels.
I've been looking into how to "solve" this and if this really is an issue and tried various combinations:
* Error summary and main heading are h1 (current solution)
* Error summary heading is h1, main heading is h2
* Error summary heading is …

Use h2 for error summary heading

---

app/views/guide_buttons.html
app/views/snippets/buttons_button_disabled.html

JAWS 15 and below don't recognise the `disabled` attribute on buttons.
This adds the `aria-disabled` attribute to make disabled buttons compatible with older screen readers.
This does not apply to other `disabled` elements. I also tested the new disabled radio buttons and checkboxes, and they are fine in older JAWS versions without this change.
I tested with JAWS 14, 15 and 17.
JAWS 17 is fine without the change and reads e.g. "Save button - unavailable" but all the others read "Save button" as if it was a normal button, not making it clear that you cannot use it. Adding `aria-disabled` fixes that. It seems redundant but is similar to our practice to add `role="main"` to our `<main>` element to support older browsers.
I couldn't test with JAWS 16 yet. In case that also doesn't support …

Make old JAWS recognise disabled buttons

---

app/views/examples/example_form_validation_multiple_questions.html
app/views/examples/example_form_validation_single_question_radio.html
app/views/snippets/form_error_multiple.html
app/views/snippets/form_error_multiple_show_errors.html
app/views/snippets/form_error_radio.html
app/views/snippets/form_error_radio_show_errors.html

Currently neither VoiceOver on iOS or macOS nor TalkBack on Android announce that there is an error when submitting a form with errors. Although we focus on the error summary box, it doesn't have the desired effect. In the iOS case it's because of [one browser bug](https://bugs.webkit.org/show_bug.cgi?id=163719) and in the macOS case because of [another browser bug](https://bugs.webkit.org/show_bug.cgi?id=171006). At least the iOS and Android issue can be fixed by adding the ARIA `role="alert"` to the error summary box.
I am not sure what the effect will be of removing the `group` role. It didn't seem to have an effect when I tested this but I would like to have someone else's opinion on this.
Changing this doesn't change the behaviour (postively or negatively) in JAWS, NVDA or VO on …

Change error summary ARIA role to "alert"

---

app/views/examples/_form_validation_implementation_advice.html
app/views/examples/example_form_validation_multiple_questions.html
app/views/examples/example_form_validation_single_question_radio.html
app/views/guide_errors.html

When a form submit wasn't successful and there are errors in the form which need to be highlighted, it is very important that every user is alerted to that as soon and effectively as possible. Although our solution for that is pretty good, it can still be improved.
Seeing users, even those with low vision, can see the big red box pretty clearly. Even in case they cannot read the text easily, they will know something is wrong. So, it's mostly the journey for blind screen reader users we should be concerned about.
Because we automatically focus on the error summary, some screen readers read that out pretty early, while others never read it. But what most screen readers read first is the title. That's what we can use to make them aware that there has been an error as soon as possible.
That's …

Reflect form validation error in title

---

app/views/guide_colour.html

The main heading for the page is “Application complete”.

Remove "Example service name" from the confirmation page

---

assets/sass/elements-documentation.scss

Use a child combinator to ensure that only headings using the
`.heading-xlarge` class - page headings in GOV.UK elements - get
larger top margins and smaller bottom margins.
This margin was affecting the typography example, which shows an
example of using the `.heading-xlarge` class.
---
---

Ensure documentation styles don't override examples

---

app/views/examples/example_date.html
app/views/examples/example_details_summary.html
app/views/examples/example_form_elements.html
app/views/examples/example_form_validation_multiple_questions.html
app/views/examples/example_form_validation_single_question_radio.html
app/views/examples/example_grid_layout.html
app/views/examples/example_icons.html
app/views/examples/example_radios_checkboxes.html
app/views/examples/example_typography.html
app/views/guide_alpha_beta.html
app/views/guide_buttons.html
app/views/guide_colour.html
app/views/guide_data.html
app/views/guide_errors.html
app/views/guide_form_elements.html
app/views/guide_icons_images.html
app/views/guide_layout.html
app/views/guide_typography.html
app/views/index.html
assets/sass/elements/_layout.scss

Reverts https://github.com/alphagov/govuk_elements/pull/225
See: https://github.com/alphagov/govuk_template/pull/321
Putting tabindex on the `<main>` element causes different problems:
* Some apps will display the browser's default focus styles around the main element
* When clicking anywhere in the page focus will return back to the top
Consider a user interacting with an input field who clicks away from it to remove
the focus style. Should they then hit tab they will be taken to the top of the page.
The [linked to browser bug](https://bugs.chromium.org/p/chromium/issues/detail?id=37721) was fixed in Apr. Testing on Safari 10.1.1 it works with VoiceOver on desktop. Testing on iOS 10.2.1 it works in mobile Safari with VoiceOver on.
More context around the issue: …

Remove tabindex from main element

---

.travis.yml

This section is no longer required now that automatic deploys are enabled in Heroku for this app.
Add a comment to travis.yml to explain how this app is deployed:
Every push to master will deploy a new version of this app. Deploys
happen automatically. Heroku will wait for CI to pass before deploying.

Remove the heroku deploy build stage from travis.yml

---

.travis.yml
scripts/create-release.sh

- Remove Heroku deploy from Travis jobs
- Make the deploy and release process clearer
Heroku is now configured to deploy the latest-release branch to the govuk-elements-sass-release app when CI passes, which means Travis no longer needs to do this.
The documentation around the Travis config is not terribly clear.
It hasn't, because Travis can't be set up locally to test with.
- Deployment / release change
- My change requires a change to the documentation.

Remove Heroku deploy from Travis jobs, update docs

---

app/views/examples/example_date.html

This documents the reason for invalid HTML in the date pattern:
A HTML validator will produce the following error for this date pattern: "Attribute pattern is only allowed when the input type is email, password, search, tel, text, or url." This is a known issue. The pattern attribute is needed to force numeric keypads on iOS devices. Type=number alone does not force the numeric keypad. Take a look at [this article](http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/) which explains the issue in more detail.
@selfthinker: do you know if this has been reported to W3?  
Fixes #551 
Tested in Chrome/FF/Safari.
- Added an explanation to a view using existing elements.

Document invalid HTML in date pattern.

---

app/views/snippets/form_input_sizes.html

Very quick fix. The "Input with class form-control-2-3 (66% width)" label on the [form elements example page](https://govuk-elements.herokuapp.com/form-elements/example-form-elements/) didn't match the input field due to a typo on the `for` attribute.

Fix label's `for` not matching input's `id`

---

app/views/guide_typography.html
app/views/snippets/typography_headings_example.html
app/views/snippets/typography_lead_paragraph.html
app/views/snippets/typography_lead_paragraph_example.html
app/views/snippets/typography_links.html
app/views/snippets/typography_lists.html
app/views/snippets/typography_paragraphs.html
app/views/snippets/typography_paragraphs_example.html

We currently use filler text in some instances on the typography page. This replaces that with English. It also improves the copy of the various list items.
Because some of the text was duplicated in two files each, I also added a filter to use just one of the files instead of two.
Unfortunately a filter block would not allow to chain multiple filters (e.g. `{% filter replace('foo', '') | replace('bar', '') %}`), so I needed to do it in a bit of a roundabout way.

Replace 'lorem ipsum' with English

---

app/views/includes/elements_tracking_body.html
app/views/includes/elements_tracking_head.html
app/views/layout.html

Google Tag Manager is currently not tracking correctly as the snippet is not placed in `head`. This issue was reported by Maria Lopez, a performance analyst on the Design System team.
According to the [docs](https://developers.google.com/tag-manager/quickstart), the snippet should be placed as close to the opening `head` tag as possible, and the `noscript` snippet be placed immediately after the opening `body` tag.
This change moves the snippet to `head` and adds a `noscript` snippet. 
The snippets have been copy pasted from the Google Tag Manager account for GOV.UK Elements and verified to be correct by Maria.
By inspecting the source and verifying that the snippets are now placed appropriately. 
Once merged into master, I will confirm with Maria that Google Tag Manager is tracking …

Move Google Tag Manager snippet to <head>. Add <noscript> snippet.

---

app/views/layout_example.html

elements_tracking no longer exists, [it was changed here](https://github.com/alphagov/govuk_elements/commit/a57a8933b8e05ad3bb1eadda8d77669b30a71e52)
however some pages still refer to it, and this pages now crash
tried to test locally but got an error about `sh: bundle: command not found` - so making this PR and hopefully Travis runs the tests

Fix references to elements_tracking.html

---

.travis.yml

A [recent update to Travis’ build environment][1] means that we now end up with Yarn 1.3.2 rather than 0.27.5.
Yarn [introduced a check against package.json’s `engines` definition in 1.0][2] which we are now failing, because we specify an engine of `>=8.1.4` for Heroku but install `4.4.7` on Travis:
```
[1/5] Validating package.json...
error govuk-elements@: The engine "node" is incompatible with this module. Expected version ">=8.1.4".
```
Installing the latest version of Node 8 on Travis should fix this.
[1]: https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/
[2]: https://github.com/yarnpkg/yarn/pull/3675/files
Mostly guesswork. But look, the tests pass!
Dependency update.
- My change requires a change to the documentation.
- I have updated the documentation …

Bump Travis’ node version

---

Gemfile
Gemfile.lock

Update Gemfile to use the latest version of govuk-lint.
The version of govuk-lint we're currently using is out of date.
1. Ran the linter manually using `npm run-script lint` and verified that the code still passed according to the linter. 
2. Made a manual change to the elements CSS to introduce a violation, and ran the command again, verifying that the violation was identified.
Dependency update
N/A

Update to latest version of govuk-lint

---

app/views/examples/example_radios_checkboxes.html

Since `display: block` was introduced for all heading classes in 8f88ccc46f7e71d2c8f4a56f4bac4beda1126cd5 the [radio example with 'headings' inside labels](https://govuk-elements.herokuapp.com/form-elements/example-radios-checkboxes/) was visually broken.
This fixes #581 by switching the `heading-small` class with the more fitting `form-label-bold` class.
### Before

Fix misaligned radio example

---

app/views/examples/example_date.html
app/views/examples/example_form_elements.html
app/views/snippets/form_date.html
app/views/snippets/form_date_show_errors.html

Remove the min and max attributes from all inputs in the various 'date' examples.
The current max attribute for the year is 2016, which means the examples are effectively two years ‘out of date’. Whilst services _might_ be expected to populate the max attribute dynamically, we’ve seen in user research that developers often copy and paste code examples blindly, and this is more likely to introduce bugs in the future than it is to help anyone.
The min and max attributes only really ‘apply’ when using the spinner (which we consciously disable using CSS), or when using browser form validation, which we advise against. The current experience in the browser is also odd – It’s possible to enter 2020 in the above example in desktop chrome and safari on MacOS but If you then use keyboard up/down …

Remove min, max attributes from date inputs

---

app/routes.js

The layout for this route and the link to it from the form elements guide were removed in 2592887e93e1df1cb767e2eaadaf341b7e62fa87 (as part of #109) but the route was left in place.
This fixes a 500 at /form-elements/example-forms, replacing it with a 404.

Remove redundant example-forms route

---

app/views/snippets/form_checkbox.html
app/views/snippets/form_checkboxes.html
app/views/snippets/form_checkboxes_disabled.html
app/views/snippets/form_hint_text.html
app/views/snippets/form_labels.html
app/views/snippets/form_radio_buttons_disabled.html
app/views/snippets/form_textarea.html

Half the snippets on the form examples page include `div.form-group` and half don't. This inconsistency causes us issues when teaching the Prototype kit. In nearly all cases our users will actually want to have the `div.form-group` for correct spacing.
NB - this means some of the visual examples now have extra whitespace at the bottom. We _could_ remove this, but since this shows the effect of the spacing div, I think it's probably better to leave in.
I've not updated any examples outside of the form examples page.
Have run it locally.
Before:
After:
Only impacts the elements style guide.
Don't think any documentation is relevant

Wrap snippets in div.form-group for consistency

---

app/views/snippets/buttons_button.html
app/views/snippets/buttons_button_disabled.html

Both `<button type='submit'>Submit<button>` and `<input type='submit' value='Submit'>` can be used to submit a form.
Historically `<input>` has been preferred because it’s better-supported by IE6 in that:
- the `submit` attribute is mandatory on `<button>`, not on `<input>`
- the `innerHTML` of a button will be submitted to the server, not the `value` (as in other browsers)
Reasons to now use `<button>` instead:
- IE6/7 support is no longer a concern (especially with deprecation of TLS 1.0 on the way)
- Because an `<input>` element can’t have children, the pseudo-element hack<sup>1</sup> used to ensure the top edge of the button is clickable doesn’t work.
Fixes #545
1. alphagov/govuk_frontend_toolkit@24e1906#diff-ef0e4eb6f1e90b44b0c3fe39dce274a4R79

Use `<button>` not `<input>`s for form submission

---

README.md
app/views/includes/deprecation_message.html
app/views/layout.html
assets/sass/elements-documentation.scss

We're adding messaging to inform users that GOV.UK elements is being superseded by GOV.UK Design System.

Add deprecation message

---

package.json

Heroku is currently failing to deploy because it's trying to use Node 12, which [Gulp 3 is not compatible with][1].
We've tried pinning to 10.x, but this causes the tests to fail because [the version of node-sass that we are using does not work with Node 10][2]. (The tests pass currently, because the node version is fixed to node 8 in travis.yml)
As node 8 is still under LTS and Elements is deprecated, we'll pin to 8 for now and revisit if it becomes a problem.
[1]: https://github.com/gulpjs/gulp/issues/2324
[2]: https://github.com/sass/node-sass/issues/1931

Pin Node.js version to 8.x

---

app/config.js
app/views/layout.html
app/views/layout_example.html
server.js
tests/wraith/snap.js

When we merge https://github.com/alphagov/govuk_elements/pull/627 we'll not set any cookies so we can remove the cookie banner.
I've had to do some undesirable hot patching to do this due to the limitations of govuk_template.

Remove cookie banner

---

README.md
app/views/includes/deprecation_message.html

We’re updating the deprecation notice in the Elements, Template and Frontend Toolkit repos, to reflect the fact that GOV.UK Design System and Frontend have now been updated to better meet WCAG 2.1.

Update GOV.UK Elements deprecation notices

---

app.json

Beginning November 2nd, 2020, the cedar-14 stack will no longer receive security updates and builds will be disabled for apps running on the cedar-14 stack.
Update to the latest Heroku-18 stack [following the Heroku guidance][1]. THe Heroku-18 stack is supported through April 2023.
[1]: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#review-apps-recommended
Closes https://github.com/alphagov/design-system-team-internal/issues/283

Update to Heroku-18 stack

---

app.json
package-lock.json
package.json
server.js

Redirect requests made over http to https by using [express-sslify](https://www.npmjs.com/package/express-sslify).
Closes alphagov/design-system-team-internal#286
(Also #582 and #439)

Enforce HTTPS on Heroku

---

config/paths.json
gulpfile.js

This PR modifies the gulp tasks to clean `/package/govuk-elements-sass/public/sass` before building it so that any removed/renamed files get correctly modified.
This issue this resolves was highlighted by `_shame.scss` still being in the package folder, despite having been deleted in https://github.com/alphagov/govuk_elements/pull/611.
This problem was identified in https://github.com/alphagov/govuk_elements/pull/635#discussion_r419287965 but was out of scope for that PR so I've split it into this separate one. 
- `npm test` passes and fails automated tests appropriately
- `gulp package` generates `/package/` with changes for publishing, removing `_shame.scss` as expected
- Fix build packaging pipeline
- My change requires no change to the documentation.
- I have read the **CONTRIBUTING** …

Delete `/package` before preparing package
