alphagov/govuk_elements

public/sass/elements/_buttons.scss
public/sass/elements/_details.scss
public/sass/elements/forms/_form-block-labels.scss

Where a focus style is defined, use the new $focus-colour variable

Use new focus-colour variable

---

README.md

Makes it easier to find the source code behind the style guide example.

Adds source code link for Rural Payments website

---

public/sass/elements/_forms.scss

This pull request:
- Adds a numbered list of contents
- Numbers individual sections
- Marks styles which are likely to change with TODO: and the proposed change.
Most of these proposed changes exist in other pull requests (by @timpaul).
This is a tidy-up of what exists, prior to making any changes.

Make forms sass clearer and propose changes

---

public/sass/elements/_elements-typography.scss
views/examples/typography.html

If people do use them, we may as well make them look good.

Add styles for horizontal rules

---

package.json

- Add helpers partial for functions
- Add px to em function and documentation

Bump govuk front end toolkit to 4.4.0

---

.travis.yml
Gruntfile.js

- Create a test grunt task
- Use this test task to check that the app runs
- If this task is run on master, deploy the app to a test Heroku app to preview.
cc. @AndrewVos

Add a travis yaml file

---

package.json

- Fix colour of logo when in `:active` state
- Add Django template
cc. @fofr.

Bump govuk template to 0.16.1

---

package.json

- Fix the [phase banner alignment](https://github.com/alphagov/govuk_frontend_toolkit/pull/266).
cc. @robinwhittleton.

Bump govuk frontend toolkit to 4.9.1

---

views/guide_colour.html

The organisation colours have been split into a new file, update the
link to this partial.
cc. @fofr

Update the link to departmental colours

---

package.json

This was missing from #255 so has been added here.

Update express to 4.13.3

---

app/views/guide_alpha_beta.html
app/views/guide_buttons.html
app/views/guide_colour.html
app/views/guide_data.html
app/views/guide_errors.html
app/views/guide_form_elements.html
app/views/guide_icons_images.html
app/views/guide_layout.html
app/views/guide_typography.html
app/views/includes/phase_banner_survey.html
app/views/index.html

Use this to replace the link to the elements Hackpad, while the survey is available.

Add a a new phase banner include with a link to the survey

---

README.md

Add link to the survey to the top of the README.
cc. @timpaul.

Add a link to the GDS front end survey

---

package.json

This should have been added in #273.

Add missing grunt-htmlentites module

---

app/routes.js
app/views/guide_style_guide.html
public/sass/elements-page.scss
public/sass/elements/_layout.scss

- Create a new style guide page
- Copy and paste content from all existing sections
- Outdent navigation to keep the main content area full width (needed to show grid layout and full page examples).

Create a style guide page

---

package.json

- Fix anchor-buttons.js to trigger a native click event, also rename to
shimLinksWithButtonRole.js to explain what it does
- Add tests for shimLinksWithButtonRole ([PR
#310](https://github.com/alphagov/govuk_frontend_toolkit/pull/310))
- Add Department for International Trade organisation ([PR
#308](https://github.com/alphagov/govuk_frontend_toolkit/pull/308))

Update govuk_frontend_toolkit to 4.16.1

---

package.json

This PR updates GOV.UK elements to use the latest version of the govuk_frontend_toolkit, 4.18.0.

Use version 4.18.0 of the govuk frontend toolkit

---

package.json

- Fix error in IE - remove trailing comma from shimLinksWithButtonRole
JavaScript ([PR
#323](https://github.com/alphagov/govuk_frontend_toolkit/pull/323)).

Use version 4.18.1 of the govuk_frontend_toolkit

---

package.json

Update the govuk_template to the latest version.
https://raw.githubusercontent.com/alphagov/govuk_template/master/CHANGEL
OG.md
- Degrade gracefully when external JS can’t be loaded ([PR
#248](https://github.com/alphagov/govuk_template/pull/248))

Bump govuk_template_jinja to 0.18.2

---

app/views/guide_colour.html

Fixes a validation error caused by a typo on a br tag.

Fix br tag

---

app/views/snippets/form_inset_checkboxes.html
app/views/snippets/form_inset_radios.html
app/views/snippets/form_radio_buttons.html
app/views/snippets/form_radio_buttons_inline.html
app/views/snippets/form_radio_inline_yes_no.html

This PR makes the examples more consistent, by ensuring that each question has a parent `.form-group` wrapper, so that validation styles can be applied. 
In some examples the `.form-group` wrapper sat inside a fieldset. It is now used outside the fieldset, to match the "Errors and validation" examples.

Ensure that a parent .form-group wraps each question

---

app/views/guide_layout.html
app/views/snippets/layout_grid_full.html

This adds an example, showing a full width column using the `.column-full` class.

Add a full-width grid column example

---

app/views/guide_data.html
app/views/snippets/data_48px_16px.html
app/views/snippets/data_48px_16px_example.html
app/views/snippets/data_80px_16px.html
app/views/snippets/data_80px_16px_example.html

This PR adds code snippets for the [data section](http://govuk-elements.herokuapp.com/data/). 
This section has examples, but they were missing the code snippets underneath.
Before:
After:
cc. @HarryTrimble, @dsingleton.

Add code snippets for data examples

---

app/views/examples/example_form_elements.html
app/views/examples/example_radios_checkboxes.html
app/views/layout_example.html
app/views/snippets/form_checkboxes.html
app/views/snippets/form_error_radio.html
app/views/snippets/form_error_radio_show_errors.html
app/views/snippets/form_inset_checkboxes.html
app/views/snippets/form_inset_radios.html
app/views/snippets/form_inset_radios_show_errors.html
app/views/snippets/form_radio_buttons.html
app/views/snippets/form_radio_buttons_inline.html
app/views/snippets/form_radio_inline_yes_no.html
public/sass/elements/forms/_form-block-labels.scss

Two small commits to improve the performance of the new radios and checkboxes.
1. remove the 300ms delay on mobile in some situations – @nickcolley can you review?
2. add the classes to recommended markup – @gemmaleigh can you review?

New radios / checkboxes performance improvements

---

app/views/guide_alpha_beta.html

These need class `.code` to apply the correct styling.

Add missing code classes

---

package.json

Increase skiplink colour contrast ([PR #263](https://github.com/alphagov/govuk_template/pull/263))

Bump govuk template to 0.19.2

---

app/views/guide_typography.html

Broken details polyfill link fixed

---

.travis.yml

As found by @colinrotherham, in Travis the correct variable to test
is TRAVIS_PULL_REQUEST_BRANCH because TRAVIS_BRANCH is the target
branch of pull requests.

Use `TRAVIS_PULL_REQUEST_BRANCH` to test build

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

It updates the pull request and issue templates, in an attempt to encourage their usage - and to provide structure to the issues raised and pull requests opened for GOV.UK elements.
- uses smaller headings 
- removes the checkboxes, as these imply that a choice is a set of things to be completed
- requests that lines that don't apply are deleted
- New feature (non-breaking change which adds functionality)

Update the Github templates for pull requests and issues

---

app/views/guide_alpha_beta.html
app/views/snippets/phase_tag_alpha.html
app/views/snippets/phase_tag_beta.html
public/sass/elements/_phase-banner.scss

This example was missing from GOV.UK elements, add an example to show
how phase tags can be used outside of the phase banner.

[For discussion] Examples of phase tags

---

README.md

<p align=center>
<br><br><br><br>
🍆 <a href="http://www.urbandictionary.com/define.php?term=Chosoe">http://www.urbandictionary.com/define.php?term=Chosoe</a>🍆 
<br><br><br><br><br>
</p>
<h1 align=center>Y U OPEN PR?</h1>
<p align=center>
<br><br>
I just did this so I could send the govuk_elements crew some fanmail <br>
under the thin veil of a content PR
<br><br>
<a href="https://camo.githubusercontent.com/ee705a03238c248114342cac82e7256cf41fafad/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f5249416e365531754a597967452f67697068792e676966" target="_blank"><img src="https://camo.githubusercontent.com/ee705a03238c248114342cac82e7256cf41fafad/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f5249416e365531754a597967452f67697068792e676966" alt="" …

README: chosoe => choose

---

app/views/layout_example.html

This PR fixes #416.
Update the example layout to use the new navigation include, as service_manual_navigation.html no longer exists.

Fix broken example pages

---

create-release.sh

Simplify the way we are pushing the latest release branch - also make it consistent with the govuk_frontend_toolkit.

Amends to create-release script to update the latest-release branch

---

README.md

Add StandardJS badge to the README.

Add StandardJS badge

---

package.json

Greenkeeper created this branch, but didn't open a PR.
I'm assuming this is related to #466. Let's try this manually.

chore(package): update node-sass to version 4.5.3

---

app/views/guide_data.html

This is adding guidance on using table captions in addition to the work in #476 as suggested by @gemmaleigh.
I'm not sure how much should go into it. If we wanted to link to anything useful, I'd link to https://www.w3.org/WAI/tutorials/tables/caption-summary/

Add guidance on using table captions

---

.travis.yml

Combine tag create, npm release and Github release steps.

Amend travis build stages

---

.travis.yml
check-lockfile.sh
yarn.lock

This pull requests adds a script - `check-lockfile.sh` to see if the Yarn lockfile needs updating.
Travis will run this script before running `yarn test`.
This has been tested using Travis in the builds below:
If the lockfile needs updating, the build stage "Run tests" will fail and will output:
"lockfile needs updating, run yarn and commit"
https://travis-ci.org/alphagov/govuk_elements/jobs/250302619#L238
Once the lockfile has been updated, the build runs successfully here:
https://travis-ci.org/alphagov/govuk_elements/jobs/250304438#L237

Check for changes to Yarn lockfile

---

scripts/check-release-version.sh
scripts/create-release.sh

Move the check to see if a tag exists into the check-release-version script.
The "create release" stage will then fail if a tag exists matching the version in packages/govuk-elements-sass/VERSION.txt.
If the tag doesn't exist, proceed to create a new tag and update the latest-release branch.

Fix check release version script

---

CONTRIBUTING.md

Update the source path of sass based on [gulpfile.js](https://github.com/alphagov/govuk_elements/blob/master/gulpfile.js#L107) and [paths.json](https://github.com/alphagov/govuk_elements/blob/master/config/paths.json#L4)
Keeps the doc updated and accurate.
Running gulp
- My change is a change to the documentation.

Update the source path of sass in the contributing document

---

package.json
yarn.lock

Closes #512.
Update run-sequence to version 2.1.0

fix(package): update run-sequence to version 2.1.0

---

scripts/create-release.sh

We’ve renamed this user as the Patterns & Tools team no longer exists.

Release as "GOV.UK Design System CI"

---

app/views/includes/elements_tracking_head.html

Issue raised this morning where a broken set of pages were on live. These were reported by an external party. Adding in the meta tag in the head to verify the site. We can then setup email alerts using Webmaster Tools to notify us when we have errors on the live site.
Simple meta tag addition to the head element. Change will have no effect on site functionality.
- New feature (non-breaking change which adds functionality)
No documentation change required. Comment in code explaining the additions meaning.

Add the Google Webmaster Tools verification code for better monitoring

---

app/views/guide_icons_images.html
app/views/guide_typography.html

This is the non-controversial part of #564 ("Improve legal text", 2 of those 5 commits) so this can be merged quicker.
* Avoid duplication of intro by rewriting intro on the icons page
* Make people aware of hidden text (because it often gets forgotten which can lead to less accessible content)
This is only a copy change.
New feature (non-breaking change which adds functionality)
The change **is** the documentation.

Make people aware of hidden text

---

app/views/guide_alpha_beta.html
app/views/guide_buttons.html
app/views/guide_colour.html
app/views/guide_data.html
app/views/guide_errors.html
app/views/guide_form_elements.html
app/views/includes/phase_banner.html

Updates broken links.
Fixes #594.
Links checked.
This is a documentation update.

Replace Hackpad links with Dropbox Paper

---

README.md
app/views/includes/deprecation_message.html

Amend messaging to make it clearer.

Amend deprecation message

---

README.md
app/views/includes/deprecation_message.html
assets/sass/elements-documentation.scss

Includes the link to now publicly available Design System

Update notice message about the Design System

---

README.md
app/views/includes/deprecation_message.html

Fixes a typo in the lead-in line in the deprecation notice.

Fix typo in deprecation notice
